torchtitan/profiling.py
* __->__ #271
As titled. Verified on experiments of 64 GPU scale that this resolves the problem #266.
=> insert barrier to profiler to resolve collectives timeout

README.md, torchtitan/parallelisms/parallelize_llama.py
1. update readme
2. small refactor to loss_parallel part
=> some misc changes

torchtitan/checkpoint.py, train.py
* __->__ #281
Adding the protocol explicitly improves the code readability.
=> inherit stateful protocol where appropriate

docs/fsdp.md
* __->__ #283
From https://github.com/pytorch/pytorch/issues/114299#issuecomment-2081823135
=> Fixed docs on HSDP sharding/replication dims

torchtitan/parallelisms/__init__.py
as titled, fixes https://github.com/pytorch/torchtitan/issues/286
=> fix 3d mesh order

torchtitan/checkpoint.py, torchtitan/config_manager.py, train.py, train_configs/debug_model.toml, train_configs/llama2_13b.toml, train_configs/llama2_70b.toml, train_configs/llama2_7b.toml, train_configs/llama3_70b.toml, train_configs/llama3_8b.toml
* __->__ #302
Summary:
This PR implements 2 different async checkpoint. The first one is to use DCP.async_save another one is to use pinned memory + a seperate process to avoid GILs issue.
=> Implement async_checkpoint

.github/workflows/unit_test_4gpu.yaml, .github/workflows/unit_test_cpu.yaml
=> Make pip install torch quiet

torchtitan/parallelisms/parallelize_llama.py
=> Fix start/stop layer parsing

train.py
=> Make seed checkpoint creation work on CPU

torchtitan/utils.py
fix BC issues
There's another pipeline bc issue :(
=> DeviceMesh BC fix

torchtitan/utils.py
=> fix missing tb logs

README.md
=> add the 8-gpu test badge and use correct links for the integration test badges

torchtitan/parallelisms/parallelize_llama.py
see https://github.com/pytorch/torchtitan/pull/397
=> SAC API follow ups to restore old behavior

train.py
* #402
* __->__ #398
- Move related code closer
- Adjust comments
=> Cosmetic changes to train.py

test_runner.py, torchtitan/models/llama/__init__.py
* #411
* #358
* #406
* __->__ #403
----
- make it possible to choose flavor per-test from test_runner.py
This is useful for PP when more layers == more possibilities for
schedules/num_stages, but we don't care about having a large model in
terms of #parameters
=> Change debugmodel to have 8 layers

estimation.py, run_llama_train.sh, torchtitan/config_manager.py
* #424
* __->__ #410
*  pytorch/pytorch#125323
Command ( --estimate.mode can be "real" or "fake"):
`./run_llama_train.sh --estimate.memory=True --estimate.mode="real"`
Output:
=> Adding FSDP Memory Tracking and Estimation

torchtitan/config_manager.py, torchtitan/parallelisms/parallelize_llama.py
=> Refactored activation checkpointing

run_llama_train.sh
* #456
* #455
* __->__ #454
* #453
Just a little code motion but it looks cleaner to me this way
=> [Cleanup] Organize run_llama_train.sh options

run_llama_train.sh, run_memory_estimation.sh
* #456
* __->__ #455
* #454
* #453
Make each script simpler to read
=> [Cleanup] Split run_llama_train.sh and run_memory_estimation.sh

test_runner.py, torchtitan/config_manager.py, torchtitan/parallelisms/pipelining_utils.py
* __->__ #490
fixes https://github.com/pytorch/torchtitan/issues/483
`python test_runner.py ./out --test pp_looped_flexible_1f1b`
=> [PP] add flexible interleaved 1f1b schedule

train.py
=> Fail when using tracer made without seed checkpoint

.github/workflows/integration_test_8gpu.yaml, test_runner.py
* #564
* __->__ #563
Add test to test runner for 3d + compile composability
=> Add 3d+compile to test runner

.github/workflows/integration_test_4gpu.yaml
=> remove float8 install as H100 is not available in CI yet

torchtitan/models/llama/model.py
=> [BE] remove unused value "max_seq_len"

torchtitan/parallelisms/pipeline_llama.py
* __->__ #616
This PR requires https://github.com/pytorch/pytorch/pull/136912, which landed on 10/11/24
=> Delete manual pp input/output tensors after adding shape inference

README.md
This PR:
1 - adds an arvix badge underneath the two CI badges that links to the titan arxiv paper.
2 - adds a two sentence section in the main body summarizing our paper with link
3 - makes a minor grammar correction regarding using latest nightly.
=> add arxiv badge and link to torchtitan paper

create_seed_checkpoint.sh, torchtitan/config_manager.py
=> Remove last instances of `data_parallel_degree`

torchtitan/profiling.py, torchtitan/utils.py
=> Various cleanups around distributed setup

README.md, torchtitan/checkpoint.py
* __->__ #657
also
- add the link to the DCP note
- fix the minor issue in https://github.com/pytorch/torchtitan/issues/617
=> add paper citation

CONTRIBUTING.md, docs/converging.md
* __->__ #695
The actual converging experiments will be updated later.
=> recommended practices for loss converging tests

torchtitan/parallelisms/parallelize_llama.py
Summary:
I mistakenly landed a debug version of #701, fixing.
Test Plan: CI
Reviewers:
Subscribers:
Tasks:
Tags:
=> fix error in #701

torchtitan/metrics.py, train.py
=> Fix `upper` calls

test_runner.py, torchtitan/parallelisms/parallel_dims.py
=> [cp] fix the device mesh access issue when CP is not used with DP

torchtitan/utils.py
Support for 3rd-party distributed backends after registering them using [torch.distributed.Backend.register_backend](https://pytorch.org/docs/stable/distributed.html#torch.distributed.Backend.register_backend)
=> Support 3rd-party distributed backend

README.md
=> Update readme with cu124 version

torchtitan/utils.py
* __->__ #733
Otherwise it complaints:
> Fatal Python error: config_init_hash_seed: PYTHONHASHSEED must be "random" or an integer in range [0; 4294967295]
Reference: https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED
=> PYTHONHASHSEED needs to be in the range of [0,2**32 - 1]

scripts/generate/test_generate.py, tests/integration_tests.py, torchtitan/utils.py, train.py
=> [BE] add integration test for the generation script

README.md
=> add CP pytorch forum post link

train.py
* __->__ #792
When developing test_pp_cp and chatting with @fegin, we realized the
freqs_cis buffers are not being handled correctly in torchtitan for the
pipelining case.
CP needs to modify the freqs_cis buffer to account for sharding on seq
dim, but in the previous titan code this was implemented incorrectly.
`model.freqs_cis` was passed to CP for sharding, but pipelining does not
use `model` at all, it uses the different stage-models contained in
`model_parts` list.  The fix is to tell CP context about each freqs_cis
buffer inside `model_parts` models.
Alternatively we could tie the freqs_cis buffers for each pp stage
together, by explicitly doing so after calling init_weights per
pp-stage.  However this is of …
=> Fix PP+CP handling freqs_cis buffer

torchtitan/checkpoint.py
=> Only init the gloo process group when necessary

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml
=> add an issue template for bug report

.github/ISSUE_TEMPLATE/bug.yml, .github/ISSUE_TEMPLATE/config.yml, docs/converging.md
It seems I can't use ghstack to land https://github.com/pytorch/torchtitan/pull/856
Creating a PR from UI for now.
=> [reland] add an issue template for bug report

torchtitan/logging.py
[ghstack-poisoned]
https://github.com/pytorch/torchtitan/pull/860
=> Add a prefix to titan logs

train.py
Integrate with PyTorch optimizer hook system instead of manually calling the hook in the training loop.
=> Use PyTorch optimiser post-hook in ModelConverter.

multinode_trainer.slurm
fix file path './train_configs/llama3_8b.toml' to './torchtitan/models/llama/train_configs/llama3_8b.tom'
=> fix : CONFIG_FILE path

README.md, torchtitan/tools/utils.py
This patch aims to add amd gpu peak flops information.
=> [rocm] add amd gpu peak flops info

README.md
Following 3aff9bd9ec509b988c372129eb167d15e7e012ca.
=> update path of `train.py` to `torchtitan/train.py`

torchtitan/config_manager.py
* __->__ #926
* #925
Fixes https://github.com/pytorch/torchtitan/issues/913
=> [Checkpointing] Change the default keep_last_k to 10

torchtitan/tools/metrics.py
This PR updates the get_metric_rank function to ensure that V Block PP Schedule (ZBVZeroBubble) is able to log it's metrics. 
Currently the metrics logging for ZBVZero Bubble pipeline schedule is broken (you get a -1 across the board for loss).
This is because V Block based schedules differ from usual PP schedules by returning their loss from rank 0 (first stage). 
All other current PP schedules return their loss from the last stage. 
Testing:
Verified on external cluster that logging is now enable for ZBV with this PR. 
Previously:
With PR:
=> Enable ZBV PP Schedule to log metrics (tensorboard, W&B)

LICENSE, README.md
Two very minor changes required by Meta legal as part of adding two new datasets.
1 - License verbiage update in readme
2 - copyright header change in BSD-License.
=> [Legal] Modifications requested by legal for adding additional datasets

torchtitan/train.py
As title, we want to add optim into metric logger so that we can log optim related metrics.
=> Add optimizer into metric logger

README.md, multinode_trainer.slurm, pyproject.toml
1. added TorchFT
2. removed fused rmsnorm
3. other minor fixes
=> README minor cleanup

docs/composability.md, docs/extension.md, torchtitan/config_manager.py
Add this document to explain the extension points in torchtitan.
The section "Extending `JobConfig`" will be updated once we support it.
=> add extension.md

torchtitan/experiments/README.md
=> contributing guidelines for the experiments folder

CONTRIBUTING.md, torchtitan/experiments/README.md
=> update main contributing.md

torchtitan/models/llama/parallelize_llama.py
as titled, encourage public import usage
=> Use public imports for FSDP2

torchtitan/experiments/deepseek_v3/model.py, torchtitan/experiments/deepseek_v3/model_config.py
Reland of #954.
For simplicity, removing code path support EP=1 (less related to this repo's purpose).
=> [DeepSeek] Remove support of EP=1 case

torchtitan/experiments/deepseek_v3/model.py
Reland of #958 
MoEs are executed sequentially across layers, and symmetric memory here is used as temporary buffers. So we can reuse it across layers, instead of creating one per MoE instance.
(No wonder I hit OOM when running larger models previously)
=> [DeepSeek] Let MoEs share Symmetric Memory across layers

torchtitan/experiments/deepseek_v3/model.py
This is significantly faster and uses much less memory. 
Have not done super deep comparisons (happy to do them if needed) but my end-to-end sft pipeline speed was increased by ~4x (~30s -> ~7s) and memory reduced by ~2x. Loss / grad norms were ~identical.
Also removed some dead code / comments happy to add back if needed.
=> [DeepSeek] Use SDPA instead of manual attention impl

torchtitan/models/llama/pipeline_llama.py
Small typo introduced recently.
=> Fix name typo in pipeline parallelism

torchtitan/experiments/__init__.py, torchtitan/models/llama/model.py, torchtitan/protocols/train_spec.py, torchtitan/tools/utils.py, torchtitan/train.py
which includes
1. `update_from_config`
2. `get_num_flop_per_token`
=> move model-specific args logic to its ModelArgs

torchtitan/experiments/USAGE.md, torchtitan/experiments/deepseek_v3/download.py, torchtitan/experiments/deepseek_v3/generate.py, torchtitan/experiments/deepseek_v3/inference.sh, torchtitan/experiments/deepseek_v3/requirements.txt
This PR adds a few 'quality of life' improvements for DS experimental:
1 - Add usage.md to help explain how to run the DS models
2 - Add requirements.txt to get up and running more quickly (for inference at least)
3 - Simplifies download.py usage by adding in a 'v2' or 'v3' option.  Usage is now "python download.py v2 / v3" to get v2 DS and v3 DS respectively.  Adds clarification if user just runs "python download.py" to show what v2 and v3 are. 
4 - Expands generate.py to take in a single user prompt making it a bit more interactive to verify things.  Also went ahead and stripped out start/end sentence tokens to make it nicer to read.  (expanded token limit to 50). 
5 - Adds inference.sh to make running inference fast - literally "bash inference.sh "your question here?"
6 - Added color …
=> [DeepSeek] improve download.py, make generate interactive with single user prompt, add inference.sh for easy inference

torchtitan/models/llama/model.py
Came across this line and noticed it could be simplified. Also improves readability.
=> Simplify ndim check in llama3 model definition

torchtitan/tools/profiling.py
Adds support for profiling `XPU` devices also.
=> [XPU] Enable profiling for XPU devices

torchtitan/components/metrics.py, torchtitan/models/llama/model.py, torchtitan/protocols/train_spec.py, torchtitan/tools/utils.py, torchtitan/train.py
The point is to let each model handle its own logic to compute
- number of parameters
- number of flops per token
=> refactor model size and flops computation into model args

torchtitan/experiments/deepseek_v3/generate.py
No substantial code change. Just moving model creation out of the generate function so that one can loop the latter.
cc @EugenHotaj
=> [BE] Move model creation out of generate function

tests/integration_tests.py, torchtitan/config_manager.py, torchtitan/distributed/pipeline.py
=> [PP] Add microbatch_size and remove num_microbatches config

tests/integration_tests.py, torchtitan/config_manager.py, torchtitan/distributed/pipeline.py, torchtitan/models/llama3/pipeline_llama.py
landing https://github.com/pytorch/torchtitan/pull/1041
=> [PP] Add pipeline_parallel_layers_per_stage config

torchtitan/train.py
Found this commented out code while debugging, this PR removes it.
=> remove commented code

torchtitan/experiments/deepseek_v3/checkpoint.py
=> [BE] Chill loggings in checkpoint load

torchtitan/components/ft.py
Device mesh classes were moved in https://github.com/pytorch/torchft/pull/157
=> [FT] update device mesh references

torchtitan/experiments/llama4/__init__.py, torchtitan/experiments/llama4/model/args.py, torchtitan/experiments/llama4/model/model.py, torchtitan/models/attention.py
Implement iRoPE for llama4
Needs the fix from PyTorch: https://github.com/pytorch/pytorch/pull/151270
=> Implement iRoPE for llama4

torchtitan/components/float8.py, torchtitan/train.py
Context: https://github.com/pytorch/torchtitan/pull/1108#issuecomment-2810813143
=> [float8] move inductor config setting to float8.py

torchtitan/experiments/flux/train.py, torchtitan/train.py
=> Fix seed checkpoint creation assertion

torchtitan/experiments/flux/dataset/flux_dataset.py, torchtitan/experiments/flux/dataset/tokenizer.py, torchtitan/experiments/flux/flux_argparser.py, torchtitan/experiments/flux/model/hf_embedder.py, torchtitan/experiments/flux/tests/test_flux_dataloader.py, torchtitan/experiments/flux/tests/test_generate_image.py, torchtitan/experiments/flux/train.py, torchtitan/experiments/flux/train_configs/debug_model.toml, torchtitan/experiments/flux/train_configs/flux_dev_model.toml, torchtitan/experiments/flux/train_configs/flux_schnell_model.toml
1. Bug fix. Fix missing fields in `arg_parser`.
2. Rebase to main folder changes,  add `ft_pg` field in train.py
=> [Flux] Fix missing field in flux argparse

torchtitan/experiments/llama4/train_configs/debug_model.toml, torchtitan/experiments/llama4/train_configs/llama4_17bx128e.toml, torchtitan/experiments/llama4/train_configs/llama4_17bx16e.toml, torchtitan/models/llama3/train_configs/debug_model.toml, torchtitan/models/llama3/train_configs/llama3_405b.toml, torchtitan/models/llama3/train_configs/llama3_70b.toml, torchtitan/models/llama3/train_configs/llama3_8b.toml
a followup fix of https://github.com/pytorch/torchtitan/pull/767
should be safe to land
=> fix float8 str list configs

torchtitan/experiments/deepseek_v3/generate.py
This PR adds two items to generate.py:
a - a time_generation decorator that can be used to auto track generation time and tokens per second
b - wraps both generation functions (with and without cuda graphs) to enable optional timing (controlled via use_timer).
Output with timing adds:
Main goal here is start seeing/monitoring the end to end impact of upcoming improvements and changes.
=> [DeepSeek MoE] create and add timing decorator to generators, show tokens per second and total generation time

torchtitan/components/tokenizer.py, torchtitan/experiments/llama4/model/args.py, torchtitan/models/llama3/model.py
https://github.com/pytorch/torchtitan/issues/1144 Synchronize the eos_id from the tokenizer to the model's eos_id
=> Fix model's eos_id

run_train.sh, torchtitan/train.py
=> test: turn off static cuda launcher

torchtitan/experiments/flux/dataset/flux_dataset.py
Refactor Flux dataloader to handle potential exception during loading dataset. The image dataset might has some corrupted image headers. To handle this, the dataloader will skip the batch if it returns error
=> [Flux] Robust dataloader to handle dataset loading issue

tests/integration_tests.py
As titled.
During my local test of Interleaved ZB on 8 A100, it hangs.
created issue https://github.com/pytorch/torchtitan/issues/1188 to track
=> [CI] disable PP Zero Bubble tests to unblock development

torchtitan/models/attention.py
Stacked PRs:
* __->__#1196
* #1190
--- --- ---
Use cudnn backend on B200
[rank0]:[titan] 2025-05-14 14:02:03,646 - root - INFO - step: 70  loss:  6.9558  memory: 46.39GiB(26.01%)  tps: 10,902  tflops: 631.39  mfu: 202.37%
Trace: 
https://fburl.com/69quru4q
[rank0]:[titan] 2025-05-14 14:52:30,850 - root - INFO - step: 70  loss:  6.9600  memory: 44.59GiB(25.00%)  tps: 12,211  tflops: 707.19  mfu: 226.66%|
https://fburl.com/garctw1u
=> Use cudnn backend on B200

tests/README.md
Context: #1202 
As I'm developing similar test for Flux model,  I realize this is important for me as well to run the tests locally and separately. 
Sorry for taking a `good-start-issue` ;)
=> Add README to run separate tests

torchtitan/config_manager.py
Stacked PRs:
* #1209
* __->__#1208
--- --- ---
[MX] By default skip MX quantization on the output layer
=> [MX] By default skip MX quantization on the output layer

torchtitan/models/attention.py
Stacked PRs:
* __->__#1209
--- --- ---
Attention small clean up
=> Attention small clean up

tests/integration_tests.py
Fixes https://github.com/pytorch/torchtitan/issues/1188
Fix is in PyTorch nightly via https://github.com/pytorch/pytorch/pull/153498. Tried these tests locally on PT nightly and they pass again.
=> [PP] Re-enable zero bubble tests

.github/workflows/integration_test_8gpu.yaml, .github/workflows/integration_test_8gpu_h100.yaml, tests/README.md, tests/integration_tests.py, tests/integration_tests_h100.py
Add H100 GPU in integration test, testing async, float8 and relative composability tests.
=> Add H100 GPU node for integration test

torchtitan/experiments/kernels/moe/indices.py
Reverts pytorch/torchtitan#1254 for the reasons @ngimel and @kwen2501 mentioned in the original PR.
It was introduced because of the issue https://github.com/pytorch/torchtitan/issues/1237
But the right way of fixing the issue is to fix my wrong way of doing permutation of both `routed_input` and `token_indices`; instead we should permute `routed_input` and unpermute.
https://github.com/pytorch/torchtitan/blob/adae6b6fd850054d6e1c04ecc2a4cf84abc68056/torchtitan/experiments/llama4/model/moe.py#L300-L305
I will send out a PR soon to fix the error in Llama 4 MoE impl.
=> Revert "[kernels] move generate_permute_indices to using exact sizes per expert needed, instead of max_len"

torchtitan/components/quantization/float8.py
MoE conversion must take place before Float8Linear conversion, otherwise the Float8Linears will
be converted back to nn.Linear (see [here](https://github.com/pytorch/ao/blob/c2a6568a04075acc371a338206216bb65536fb27/torchao/quantization/quant_api.py#L294-L299)).
- Add warning in torchao when this happens, or find a better way to avoid this.
=> [float8 moe training] Do MoE conversion before Float8Linear conversion to avoid unconverting Float8Linears 

torchtitan/components/dataloader.py, torchtitan/experiments/flux/dataset/flux_dataset.py, torchtitan/experiments/flux/job_config.py, torchtitan/experiments/flux/sampling.py, torchtitan/experiments/flux/tests/test_generate_image.py, torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py, torchtitan/experiments/flux/train_configs/debug_model.toml, torchtitan/experiments/flux/train_configs/flux_dev_model.toml, torchtitan/experiments/flux/train_configs/flux_schnell_model.toml
Migrating the checkpointing of the flux dataset to use huggingface's faster api for IterableDatasets.
=> Migrating flux checkpointing to hf api

torchtitan/experiments/flux/sampling.py
passing dtype argument to preprocess_data in generate_image
=> fixing dtype in flux eval

torchtitan/components/ft.py
Summary:
enable creating a separate outer optimizer for each of the parameter fragments for streaming diloco
=> create multipe outer optimizers for diloco

README.md, docs/release.md
=> update documentation for release

torchtitan/models/deepseek_v3/infra/parallelize.py
Without this PR, FlexAttention mask function will receive a mixed of plain tensors and DTensors.
Given that FlexAttention + DTensor story is not clear, let's always convert to plain tensors when feeding things into FlexAttention / SDPA.
=> [deepseek] fix FlexAttention + TP

tests/integration_tests.py
These should be fixed now that https://github.com/pytorch/pytorch/pull/159084 has landed
=> Re-enable pipeline parallel tests

torchtitan/experiments/forge/engine.py
Copied from github.com/pytorch/torchtitan/pull/1441, tested manually via forge
=> Fixes the sd adapter in forge experiments

docs/checkpoint.md
=> checkpoint.md

torchtitan/experiments/llama4/infra/parallelize.py, torchtitan/models/deepseek_v3/README.md, torchtitan/models/deepseek_v3/infra/parallelize.py
verified that torch.compile works.
However, I didn't see async TP in trace.
cc @danielvegamyhre @fegin Could you help take a look?
=> [DeepSeek] add torch.compile + async TP

torchtitan/models/moe.py
self.score_function should be self.score_func
=> Fix variable name in NotImplementedError message

torchtitan/components/validate.py, torchtitan/experiments/flux/validate.py
Follow up for https://github.com/pytorch/torchtitan/pull/1634
Updated the warning message according to [Jiani's suggestion](https://github.com/pytorch/torchtitan/pull/1634#pullrequestreview-3161237853)
cc @wwwjn
=> update warning message

torchtitan/experiments/llama4/train_configs/debug_model.toml, torchtitan/models/deepseek_v3/train_configs/debug_model.toml, torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml, torchtitan/models/deepseek_v3/train_configs/deepseek_v3_671b.toml
Thanks for @anana10c contribution, https://github.com/pytorch/torchtitan/pull/1644 has helped catch several toml issues. This PR fixes these issues.
=> Fix toml files

.github/CODEOWNERS
=> Add Forge Code Owner

torchtitan/experiments/qwen3/README.md, torchtitan/experiments/qwen3/model/args.py, torchtitan/experiments/qwen3/train_configs/qwen3_1.7b.toml
Contents:
1. Minor fix in qwen 0.6b training config
2. Add qwen 1.7b training cofnig
3. Fix the number of parameters calculation when weight tying is enabled
=> [Qwen3] Add 1.7b Config

README.md
=> Fix CI link in README

torchtitan/components/loss.py, torchtitan/config/job_config.py, torchtitan/experiments/flux/loss.py, torchtitan/experiments/llama4/infra/parallelize.py, torchtitan/experiments/qwen3/infra/parallelize.py, torchtitan/experiments/simple_fsdp/deepseek_v3/parallelize.py, torchtitan/experiments/simple_fsdp/llama3/parallelize.py, torchtitan/experiments/vlm/infra/parallelize.py, torchtitan/models/deepseek_v3/infra/parallelize.py, torchtitan/models/llama3/infra/parallelize.py
Stacked PRs:
* __->__#1768
--- --- ---
=> config compile backend
