README.md

Showcase where the product positioning lies more clearly

---

torchtitan/checkpoint.py
train.py

* __->__ #275
If not checkpointed, lr scheduler's step always starts from 0 after loading checkpoint, which is wrong.

fix lr scheduling by checkpointing scheduler

---

torchtitan/config_manager.py
torchtitan/float8_linear.py

Add more the possible options in the configs and add a note on how to get the dependency at the top of the file.

Add more Float8 description

---

.github/workflows/integration_test_periodic.yaml
README.md

Runs the integration test hourly and updates signal badge. Tested on existing integration test. I will update the badge with periodic test signal once workflow has landed in this PR.

Add periodic integration test with signal

---

torchtitan/utils.py
train.py

* __->__ #280
Per suggestion in #274:
This PR removes embedding from number of parameters calculation, because embedding op doesn't do matmul.
This PR follow the industry convention (PaLM paper, nanoGPT, Megatron, etc.) and uses a factor of 12 in the self-attention part, even when causal attention is enabled.

exclude embedding in MFU computation

---

.github/workflows/integration_test_periodic.yaml
.github/workflows/unit_test_4gpu.yaml
.github/workflows/unit_test_cpu.yaml
README.md

* __->__ #295
we can remove `pip install .` before it's supported / needed.

remove unnecessary install of torchtitan

---

torchtitan/models/llama/model.py

* #161
* __->__ #298
This appears to be a holdover from a previous way the initialization
worked.
freqs_cis should already be on gpu device after initialization.
See [this conversation](https://github.com/pytorch/torchtitan/pull/161/files#r1588516210) for reference.

Remove unnecessary .to() inside model forward

---

torchtitan/profiling.py
train.py

Summary:
The profiler currently maintains a counter locally and that counter is not synchronized with the checkpointed train step. This PR fixes the issue.

Fix the incorrect step log for profiler after resuming from a checkpoint

---

train.py
train_configs/llama3_8b.toml

as titled. This could make 1-D and 2-D works with the lastest main build. thanks @bdhirsh for all the fixes!
We should figure out why dynamic shape gets turned on as a follow up

turn off dynamic shape for torch.compile

---

torchtitan/models/llama/model.py

* __->__ #299
some minor cleanups

Renamed `bsz` to `bs` for consistency; removed dead code

---

torchtitan/checkpoint.py
torchtitan/config_manager.py
train.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

* __->__ #313
Summary:
This PR implements 2 different async checkpoint. The first one is to use
DCP.async_save another one is to use pinned memory + a seperate process
to avoid GILs issue.

Implement async_checkpoint

---

torchtitan/parallelisms/parallelize_llama.py
train_configs/llama3_8b.toml

as titled, we can directly specify the rowwise parallel embedding output layouts be shard on sequence dim, so that we don't need the first layer prepare input.
Switching to output_layouts = Shard(1) would also trigger reduce_scatter instead of allreduce for embedding layer, which could give some small perf wins

simplify embedding + first transformer block TP

---

torchtitan/checkpoint.py

.metadata may be missing in some checkpoints if some ranks did not checkpoint properly. This PR filters out checkpoints that do not have .metadata in them.

Only include checkpoints that have .metadata written

---

torchtitan/models/llama/model.py

* #318
* #322
* __->__ #321
Unchanged: we precompute freqs_cis for max_seqlen, >> seqlen for a given
batch.
Changed: instead of slicing self.freqs_cis down to seqlen at top level
transformer based on the input token shape, we slice it down to seqlen
inside a transformer layer after we have re-expanded to the full seqlen
in cases where TP has sharded across seqlen.
In the PP case, stage 1's input may be seqlen/TP instead of seqlen, but
we do not generally know this.  That makes it hard for stage1 to slice
freqs_cis correctly.  It's easy to do the slicing deeper inside, since
at that point we do know the full seqlen unambiguously.
Note: the full self.freqs_cis is stored in memory either way, and the
thing passed …

Refactor freqs_cis slice to be safer for PP

---

torchtitan/models/llama/model.py
torchtitan/parallelisms/parallelize_llama.py

* #318
* __->__ #322
* #321
A few small changes here lets manual PP frontend 'reconfigure' a whole
transformer model to a stage's portion simply by setting undesired
layers to None (in cases of top level layers) or deleting them from the
ModuleDict (for 'layers.*').
These changes don't impact the FQNs of the remaining layers, which is
critical for checkpoint load/save compatibility.

Make Transformer tolerate missing layers for PP

---

.github/workflows/unit_test_4gpu.yaml
.github/workflows/unit_test_cpu.yaml
requirements.txt
test_runner.py

* #318
* __->__ #325
This moves over to using the standard pytorch CI job template.  ([doc](https://github.com/pytorch/test-infra/wiki/Writing-generic-CI-jobs)).
The general advantages should be that we can more easily add features or options in a maintained way.  A specific reason is becuase I was not able to ssh-debug on our old CI and @seemethere mentioned that the 'generic workflow' is where the CI SSH support lives.
**SSH**
Use ssh just like pytorch/pytorch CI:
**Artifacts Uploading**
The job.dump_folder for each test is uniquely named and bundled into an `outputs.zip` which can be downloaded from github actions UI:
* profiles
* checkpoints
* flight recorder comm_dumps (if any hang happened during CI)
To …

Use torch generic workflow for CI, add ssh, artifacts

---

torchtitan/checkpoint.py

* __->__ #333
"Async checkpointing with pinned memory" requires a very recent pytorch nightly. Since we don't want to fix a nightly in `requirements.txt`, and this checkpointing option is not the default one, let's not import it under all circumstances.

[checkpointing] import async checkpoint with pinned memory only when needed

---

test_runner.py

* #318
* __->__ #343
* #342
also wrap logic into functions and clean up global vars

Make  test_runner.py warn on non-empty output dir

---

torchtitan/checkpoint.py
torchtitan/config_manager.py
torchtitan/parallelisms/parallelize_llama.py

* #345
* #344
* #318
* __->__ #348
add training.mixed_precision_param and .mixed_precision_reduce options
refactor a util to map strings to torch dtypes

Expose mixed_precision dtype arguments

---

.github/workflows/integration_test_periodic.yaml
torchtitan/datasets/hf_datasets.py

* __->__ #353
1. use the same generic torch CI workflow for periodic integration test, as in #325 for cpu/gpu unit tests.
2. `StatefulDataloader` is not in `torchdata` official release yet. Print helper message if user doesn't have a recent nightly installed.

fix periodic integration test and add helper message on torchdata import failure

---

test_runner.py

* #345
* #344
* __->__ #352
previous change to use logging from torchtitan caused stdout not
to show up.

Make test_runner use separate logger with default INFO

---

multinode_trainer.slurm

cc @wanchaol @lessw2020 @wconstab

Fix llama_13b.toml -> llama2_13b.toml in multinode_trainer.slurm

---

torchtitan/parallelisms/parallelize_llama.py

* #345
* #344
* __->__ #354
mostly harmless bug, since output shape of last layer is not used for
send/recv purpose, the runtime value overrides it no matter what value
you configured it with.
However, since adding in/out shape validation to pipeline lib in torch,
this raises an error and has to be fixed.

Fix bug in PP output layer shape

---

torchtitan/parallelisms/parallelize_llama.py

* #344
* __->__ #356
APIs conform to the pytorch rules.  This PR should be able to land
safely after tonight's nightly pytorch build which includes the above
PR.

Update pipelining import after change on pytorch

---

.gitignore

After updating today, I found a whole slew of various new temp files clogging up my source tab. 
This PR screens these out so that they don't accidentally get added in a PR and keeps your source tab change count correct. 
Example of issue without this PR:
vs with this PR:

update .gitignore to screen out slew of new temp files

---

test_runner.py
torchtitan/parallelisms/parallelize_llama.py

* #362
* __->__ #371
This PR fixes the issue mentioned [here](https://github.com/pytorch/pytorch/pull/126653#issuecomment-2130504712):
"Module object has no attributed items."
The reason is, a split `ModuleDict` is no longer a `ModuleDict`.
It would be more generally applicable if we use `named_children()` and `register_module()` to access and update submodules.

Use general way to access and update submodules

---

.ci/docker/requirements.txt
train_configs/debug_model.toml

* __->__ #372
`torch 2.2.0.dev` is too stale to be useful.
For CI, since we will install nightly anyway, this avoids storing the old version in the docker image.
update: per @wanchaol's comment, adding 2.3.0 as it's the lastest stable version.
some comments:
1. Putting `2.4.0.dev` there requires `--index-url https://download.pytorch.org/whl/nightly/cu121`. We don't want to specify `cu121` since different people might have different cuda support. However, if we remove that, as @awgu  previously explored, it will try to download everything and then select. So we'd rather let user install latest nightly.
2. Installing a stable `torch` version like 2.3.0 will install `triton`, whereas installing a nightly 2.4.0.dev …

remove old torch dependency in requirements.txt

---

test_runner.py

Usage:
`--test <test_id>`
Acceptable values: `test_id` in `build_test_list` (default: all)
Example:
```
rm -rf outputs && python test_runner.py outputs --test pp_gpipe
```

Add --test option to specify test to run

---

torchtitan/config_manager.py
torchtitan/metrics.py
torchtitan/utils.py
train.py

* __->__ #383
Avoid complicating the ux and leave the status quo of 2 user-selectable
behaviors:
- log from rank 0 (the default)
- log from all ranks (not the default)
Modify the meaning of 'log from rank 0' to log from rank 0 in
non-pipeline parallel runs, and log from the local rank 0 within the
last pipeline-parallel stage group if pp is enabled.  (note: earlier
pipeline stages still produce some metrics like mfu/memory, but do not
compute loss.)

Make metrics logging work for pipeline parallelism

---

test_runner.py
torchtitan/config_manager.py
train.py

With these three PRs landed, we can now support the option fused=True in torchtitan for Adam and AdamW optimizer. 
https://github.com/pytorch/pytorch/pull/125369
https://github.com/pytorch/pytorch/pull/126423
https://github.com/pytorch/pytorch/pull/126750
Run performance evaluation on 8 A100 DevGPU: 1000 steps on 1D DP default [llama_8b.toml](https://github.com/pytorch/torchtitan/blob/main/train_configs/llama3_8b.toml). 
Observation: 
For `fused = True` and `fused = False`, we observed similar loss curve and memory usage.
wps is + ~100 and mfu is + 1.5-2% when fused = True. 
Below are the logs for the last 100 steps for both.
```
**Fused = False**
[rank0]:2024-06-05 12:45:06,227 - root - INFO - Finished dumping traces in 0.37 seconds
[rank0]:2024-06-05 12:45:37,677 - root - INFO - step: …
```

[torchtitan][optim] Add fused as an option in train config

---

train.py

Updates the behavior to call foreach when we are not using fused for the optimizer

Abstract out out optimizer params and update foreach calling convention

---

test_runner.py
torchtitan/parallelisms/parallelize_llama.py

* __->__ #362
forgot to enable tracer for tracer test in the last PR

Fix 1D PP tracer test

---

train.py

logits=(bs, seq_len, vocab_size). call `del logits` to free it before backward

del logits=(bs, seq_len, vocab_size) to save 3.9G memory

---

torchtitan/parallelisms/parallelize_llama.py

as titled, SAC moved to a different public API, move to the new API to avoid CI breaking

Fix SAC BC breaking and renaming to ac_freq

---

.ci/docker/dev-requirements.txt
test/test_fused_rms_norm.py
test_runner.py
torchtitan/models/norms.py
torchtitan/parallelisms/parallelize_llama.py

Summary
This PR enables the use of TritonFusedRMSNorm with Tensor Parallel with 7%-8% performance gain compared to RMSNorm with TP. #364

enable TritonFusedRMSNorm with local_map annotation

---

torchtitan/parallelisms/parallelize_llama.py

* __->__ #402
Breaking up `parallelize_llama` into:
- `apply_tp`
- `apply_ac`
- `apply_compile`
- `apply_dp`
This is for functionality reuse in inference cases, because one would not need activation checkpointing or DP there.
Can also improve code modularity and readability.

Break down parallelize_llama for inference cases

---

torchtitan/checkpoint.py
torchtitan/lr_scheduling.py
torchtitan/parallelisms/parallelize_llama.py
torchtitan/parallelisms/pipelining_utils.py
torchtitan/utils.py
train.py

* #411
* #358
* __->__ #406
When using pipeline parallelism, a common technique  for reducing bubble
size is to use schedules that specify more than one model chunk per
physical rank.  e.g. pp degree 4 could have 8 pipeline stages, and rank
0 could have stage 0 and stage 4.
To generalize this concept without forking too much code in train.py, I
make 'model_parts' a new container that either contains one model for
non-PP or simple PP cases, and contains multiple model parts for complex
PP cases.
In general, this is tractable becuase we treat each model part the same:
we create one optimizer per model part, and one lr scheduler per
optimizer.  We apply spmd and compile individually to each model part.
The general …

Prepare train.py for model chunks for pipelining

---

train.py

train.py renamed `model` to `whole_model` https://github.com/pytorch/torchtitan/pull/406
fp8 still use `model` thus report error on `model not defined`. this PR fixed it
`build_fp8_linear(whole_model, job_config)`

whole_model for fp8 

---

torchtitan/profiling.py

* __->__ #419
`record_shapes=True` should have negligible extra runtime overhead and does not bloat the trace file. We should set it since it helps understanding traces.

Set `record_shapes=True` for profiler

---

torchtitan/models/llama/model.py

* __->__ #418
**Overview**
This PR replaces `x[:, :, :, None, :]` with `torch.unsqueeze(x, dim=3)` to avoid unnecessary device copies and fill kernels in backward (namely, 4 fills and 4 copies with shape `(bs, seq_len, n_kv_heads, head_dim)`).
**Traces**
Existing forward (CPU):
Existing backward (CPU):
Existing backward (GPU):
Each `aten::slice` in forward leads to a `SliceBackward0`, which is `aten::zeros` -> `aten::copy_`. 
New forward (CPU):
New backward (CPU):
New backward (GPU): has no more fill kernels and device copies
**Test Plan**
- Add `torch.manual_seed(0)` and `torch.use_deterministic_algorithms(True, warn_only=False)` at the beginning of `main` in `train.py`
- `CUBLAS_WORKSPACE_CONFIG=:4096:8 …

Improved `repeat_kv` eager perf

---

estimation.py
run_llama_train.sh
torchtitan/config_manager.py

* __->__ #425
*  pytorch/pytorch#125323
Command ( --estimate.mode can be "real" or "fake"):
`./run_llama_train.sh --estimate.memory=True --estimate.mode="real"`
Output:

Adding FSDP Memory Tracking and Estimation

---

.ci/docker/requirements.txt
test_runner.py

* __->__ #426
Adds an integration test for `FSDPMemTracker` which will help keep `estimation.py` in sync with `train.py`.
`python test_runner.py test_outputs  --test fsdp2_mem_tracker`
[Integration test CI output](https://github.com/pytorch/torchtitan/actions/runs/9669866463/job/26677362430?pr=426#step:12:4449) (Unzoom for better viewing):
cc: @gnadathur

Adding integration test for FSDP Memory Tracking and Estimation

---

train_configs/debug_model.toml

* __->__ #430
Currently memory profiler would profile and dump memory snapshots for every single iteration (for details see https://github.com/pytorch/torchtitan/pull/395#pullrequestreview-2121075514). Even for `debug_model`, this costs around 20 seconds. Let's disable it by default, until per `prof_freq` profiling and dumping is enabled (tracked in #422).

by default disable heavy memory profiling

---

torchtitan/config_manager.py
torchtitan/parallelisms/parallelize_llama.py
train.py

* __->__ #429
This PR adds the option to turn on async-TP (`--experimental.enable_async_tensor_parallel`). The feature is currently implemented as compiler passes on relevant patterns, so the option is currently only effective when compile is enabled.
Some trace samples from llama3_70b with tp degree=8:
**all-gather -> qkv projection**
Baseline:
With async-TP:
**ffn -> reduce-scater**
Baseline:
With async-TP:
**all-gather -> ffn**
Baseline:
With async-TP:

Add the option to turn on async-TP

---

estimation.py
run_llama_train.sh
test_runner.py
torchtitan/config_manager.py

* __->__ #435
* #426 
* #425 
As per suggestions from @tianyu-l in #425, the config options are now:
`./run_llama_train.sh --memory_estimation.enabled --memory_estimation.disable_fake_mode`
`FakeTensorMode` is enabled by default. User needs to use the config option `--memory_estimation.disable_fake_mode` to disable it explicitly.

Modifying memory estimation options and minor changes

---

torchtitan/parallelisms/parallelize_llama.py

* __->__ #438
Since we do not want to directly land model code change for Sequence Parallel acceleration, this PR adds a comment to point to the example code change in another PR #437 which won't be landed.

add comment pointing to Sequence Parallel optimization example

---

torchtitan/config_manager.py
torchtitan/float8_linear.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

Summary:
After https://github.com/pytorch-labs/float8_experimental/pull/300, `Float8Linear` with default settings is equivalent to `Float8DynamicLinear`. This PR changes `torchtitan` to use `Float8Linear`.
To support the new UX of `float8_experimental` better, I also switched the `fp8_linear` configuration to be a boolean on whether to swap the linears or not. In the future we can add new options on how to configure each linear (scaling type, scaling granularity, etc) - saving that for a future PR.
Test Plan:
```
// run baseline (Float8DynamicLinear) for llama3_8b for 50 iterations on 4 GPUs,
// verify performance and loss values do not change meaningfully between
// baseline and this PR
// baseline (before this PR)
// 1. compile, bf16
// 2. compile, float8
// 3. compile, float8, …
```

switch float8 logic from Float8DynamicLinear to Float8Linear

---

torchtitan/parallelisms/parallelize_llama.py

* #449
* #448
* #447
* #446
* #445
* __->__ #444
This flag does not exist anymore in latest PyTorch.

Removed `_experimental_support_context_fn_in_torch_utils_checkpoint`

---

torchtitan/parallelisms/parallelize_llama.py

* #449
* #448
* #447
* #446
* __->__ #445
* #444
- Llama uses pre-norm (norm before attention and before FFN), so we can move these up.
- The root norm is before output, so we can swap this order too.

Reordered TP parallel plan to follow execution order

---

torchtitan/parallelisms/parallelize_llama.py

* #449
* #448
* #447
* __->__ #446
* #445
* #444

Made some stylistic changes to `apply_dp`

---

estimation.py
test_runner.py
torchtitan/config_manager.py
torchtitan/models/norms.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

* __->__ #442
On Llama3 8B model, no AC
`compiled_rmsnorm` is ~9% faster than `rmsnorm`, but ~2% slower than `fused_rmsnorm`.
Please see below for details.
rmsnorm
compiled_rmsnorm
fused_rmsnorm

compiled RMSNorm

---

torchtitan/parallelisms/parallelize_llama.py

Renamed parallel styles for transformer block weights

---

torchtitan/config_manager.py
torchtitan/parallelisms/parallelize_llama.py

* __->__ #449
* #448
* #447
- Add type annotations for `parallelize_llama.py` -- how do we enable mypy?
- Move validation checks to `config_mananger.py` to error early (before building device mesh, dataloader)
~~For discussion: We want to avoid duplicating checks in `parallelize_llama.py` and `config_manager.py`. One way to do this is to change some config attributes to become enums (so we do not need to have a fallback `else: raise ...` for invalid values). I am not sure how this works exactly though.~~ Let us keep the checks close to usage.

Added some type annotations and some other stylistic changes

---

create_seed_checkpoint.sh
multinode_trainer.slurm
run_llama_train.sh

* #456
* #455
* #454
* __->__ #453
libuv is now enabled by default.
we can proably do without the educational blurb there, and don't need
the env either since the default has landed.

[Cleanup] Remove libuv from run_llama_train.sh

---

create_seed_checkpoint.sh
run_llama_train.sh
run_memory_estimation.sh

* __->__ #456
* #455
* #454
* #453
This argument seems to be left over from older times- it is not used
anywhere in the codebase.

[Cleanup] Remove unused TRAINER_DIR

---

README.md

* __->__ #457
looks like this, and the links work

Add educational code pointers to top level README

---

estimation.py
test_runner.py
torchtitan/config_manager.py
torchtitan/float8_linear.py
torchtitan/parallelisms/parallelize_llama.py
train.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

we have landed fp8 all-gather optimizations in float8_experimental https://github.com/pytorch-labs/float8_experimental/pull/266/
this PR proposes torchtitan changes. also include fp8 in CI
```
from float8_experimental.fsdp_utils import precompute_float8_dynamic_scale_for_fsdp
model(input).sum().backward()
optim.step()
precompute_float8_dynamic_scale_for_fsdp(model)
```
FSDP2 fp8 all-gather are added to CI
```
CONFIG_FILE="./train_configs/debug_model.toml" ./run_llama_train.sh --training.enable_fp8_linear
CONFIG_FILE="./train_configs/debug_model.toml" ./run_llama_train.sh --training.enable_fp8_linear --training.enable_fsdp_fp8_all_gather
CONFIG_FILE="./train_configs/debug_model.toml" ./run_llama_train.sh --training.enable_fp8_linear --training.enable_fsdp_fp8_all_gather …
```

enable FSDP2 + fp8 all-gather and fix TP fp8 all-gather

---

test_runner.py
torchtitan/config_manager.py
torchtitan/float8_linear.py
torchtitan/parallelisms/parallelize_llama.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

Summary:
1. standardizes on `float8` instead of `fp8` for config names
2. removes usage of non-public objects such as `Float8Linear`
Test Plan:
```
with-proxy NGPU=1 CUDA_VISIBLE_DEVICES=7 CONFIG_FILE="./train_configs/debug_model.toml" ./run_llama_train.sh --training.compile --training.enable_float8_linear
```
Reviewers:
Subscribers:
Tasks:
Tags:

clean up float8 configs in torchtitan

---

estimation.py
test_runner.py
torchtitan/config_manager.py
torchtitan/parallelisms/__init__.py
torchtitan/parallelisms/parallelize_llama.py
train.py

* __->__ #432
Summary:
Address the comments in https://github.com/pytorch/torchtitan/pull/319 and resubmit the PR to fit the current code base.
Test Plan:
```
CONFIG_FILE=./train_configs/debug_model.toml ./run_llama_train.sh --comm.train_timeout_seconds=3600   --training.tensor_parallel_degree=1 --training.data_parallel_degree=8 --experimental.data_parallel_type=ddp --training.steps=1000 --metrics.log_freq=10 --profiling.profile_freq=1000
```
**DDP tensorboard log**
**FSDP tensorboard log**

Add support of DDP and experimental CompiledAutograd

---

test_runner.py
torchtitan/float8_linear.py
torchtitan/parallelisms/parallelize_llama.py

**keep model.output as nn.Linear**: it's a common practice to NOT apply fp8 on final output layer
* specify `skip_fqn_list` in swapping
* when applying TP to model.output, use plain `ColwiseParallel` instead of `Float8ColwiseParallel`
credit to @awgu, we do not need tokentizer vacab size to be divisible by 16 https://github.com/pytorch/torchtitan/issues/461
1D TP + float8 all-gather, eager mode: `CONFIG_FILE="./train_configs/debug_model.toml" NGPU=4 ./run_llama_train.sh --training.enable_float8_linear --training.data_parallel_degree 1 --training.tensor_parallel_degree 4`
1D TP + float8 all-gather, compile mode: `CONFIG_FILE="./train_configs/debug_model.toml" NGPU=4 ./run_llama_train.sh --training.enable_float8_linear --training.data_parallel_degree 1 --training.tensor_parallel_degree 4 …

[float8] keep model.output as `nn.Linear` (high precision, not fp8)

---

test_runner.py

per discussion from https://github.com/pytorch/torchtitan/pull/469#issuecomment-2240258083
we are planning BC breaking changes in float8_experimental. remove CI for FSDP2 + fp8 all-gather for now. When public APIs are finalized, we can discuss bringing it back

remove CI for FSDP2 + fp8 all-gather

---

torchtitan/parallelisms/parallelize_llama.py
train_configs/debug_model.toml

This PR adds some enhancements for supporting async tp:
1 - if async tp is active, auto updates the torch.dynamo cache limit to 10K.  If this is not updated, async tp will not be activated on larger models as it will quietly stop compilation due to 'cache limit reached' with no info for the user.
This config update is logged. 
2 - if async tp is enabled, verifies that torch.compile is set to true for this job config.  If not, it warns and then activates torch.compile to ensure user gets working async tp. (see WARNING in below screenshot) 
3 - Updates the 'Applied Tensor Parallel' to the model to be 'Applied Async Tensor Parallel' when async tp is active to make it clear in the logs which TP is active.  (see above screenshot)

dynamically update torch.compile cache config to ensure async tp support, enhance async tp UX

---

torchtitan/parallelisms/parallelize_llama.py

* __->__ #460
DCP recently added safeties to avoid using it for 2D/3D since strided
sharding (a feature needed for safe 2D/3D resharding) is not ready yet.
PP uses DCP to load a seed checkpoint.  Disabling the safety mechanism
is enough to make 3D/PP still work (for the case where we train from the
beginning or do not re-shard.
(Resharding refers to saving a checkpoint from one world
size/parallelism config and loading/resuming under a different one).

Fix 8gpu PP failure due to 2D DCP disablement

---

torchtitan/float8_linear.py

Summary:
float8_experimental landed various BC-breaking UX changes last week. This PR updates torchtitan to work with the version of float8_experimental after
https://github.com/pytorch-labs/float8_experimental/pull/332 and https://github.com/pytorch-labs/float8_experimental/pull/337
Test Plan:
```
with-proxy CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 NGPU=8 CONFIG_FILE="./train_configs/llama3_8b.toml" ./run_llama_train.sh --training.enable_float8_linear --training.compile
```
Reviewers:
Subscribers:
Tasks:
Tags:

update float8 integration after UX changes

---

estimation.py
test_runner.py

* __->__ #485
When `run_llama_train.sh` was simplified, we moved the launch of memory estimation and tracking to `run_memory_estimation.sh`. But changing the `test_runner.py ` was missed which in-turn caused the integration test to be a no-op. This PR re-enables integration tests for the `FSDP2MemTracker`. 
Also syncs `estimation.py` with `train.py` since it went out of sync due to testing being skipped.

Re-enable FSDP2 Mem Tracker integration tests

---

torchtitan/lr_scheduling.py

* #488
* __->__ #487
no need for global vars when can use `partial`
fixes https://github.com/pytorch/torchtitan/issues/29

Used `partial` instead of global vars for LR scheduling

---

torchtitan/config_manager.py
torchtitan/float8_linear.py
train.py

Summary:
Adds config options to configure float8 scaling type for input, weight, grad_output.
Performance is not ideal yet, but that's because we have not optimized it.
Test Plan:
```
// repeat for input, weight, grad_out
with-proxy CONFIG_FILE="./train_configs/llama3_8b.toml" ./run_llama_train.sh --training.enable_float8_linear --training.float8_scaling_type_weight delayed --training.compile
```
Reviewers:
Subscribers:
Tasks:
Tags:

make float8 scaling type configurable

---

test_runner.py
torchtitan/config_manager.py
torchtitan/parallelisms/pipelining_utils.py

This was approved in https://github.com/pytorch/torchtitan/pull/490, but merged into the wrong branch, merging this into main

[PP] add flexible interleaved 1f1b schedule #490

---

.github/workflows/integration_test_4gpu.yaml
torchtitan/config_manager.py
torchtitan/float8_linear.py
torchtitan/parallelisms/parallelize_llama.py

Summary:
The `float8_experimental` repository moved to `torchao.float8` in https://github.com/pytorch/ao/pull/551
This PR updates `torchtitan` to use float8 from the new location.
Test Plan:
```
with-proxy CONFIG_FILE="./train_configs/debug_model.toml" ./run_llama_train.sh --training.enable_float8_linear --training.compile
```
Reviewers:
Subscribers:
Tasks:
Tags:

move float8 callsites to torchao.float8

---

torchtitan/parallelisms/parallelize_llama.py
train.py

* #496
* __->__ #495
* #494
Previous all subroutines called by `parallelize_llama` have full access to `world_mesh`, `parallel_dims`, `job_config`, which exposes unnecessary global information. It makes things error-prone and negatively impacts code readability.
This PR refactors the method signatures to only use required fields and resolves the issue.

[BE][2/n] use proper method signatures in parallelize_llama

---

estimation.py
torchtitan/config_manager.py
torchtitan/float8_linear.py
torchtitan/parallelisms/parallelize_llama.py
train.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

* __->__ #496
* #495
* #494
This PR fixes and cleans up the logic in `float8_linear.py`.
Now we only need to expose a `float8_handler` in `train.py`. It will be a no-op if float8 is not enabled. This helps reduce number of imports as well.
Move float8 configs into a dedicated section, since there are many knobs.

[BE][3/n] wrap fp8 logic using Float8Handler

---

train_configs/llama3_405b.toml

As title, use `8e-5` rather than `0.8e-4`.

[EZ][405B] Use scientific notation for 405B model lr

---

README.md
estimation.py
torchtitan/float8.py
torchtitan/metrics.py
torchtitan/parallelisms/__init__.py
torchtitan/parallelisms/parallel_dims.py
torchtitan/parallelisms/parallelize_llama.py
torchtitan/parallelisms/pipeline_llama.py
train.py

* #501
* #500
* __->__ #499
- `parallelize_llama.py` has become a almost 600 lines file, which is too big to read. Let's separate the PP part out, as it does not interact with the rest spmd code.
- Making `ParallelDims` into a standalone file, as it's used by `parallelize_llama.py` and `pipeline_llama.py`.
- Renaming `float8_linear.py` to `float8.py` and adding it to the `README.md`
- Some other minor changes.

[BE][4/n] split pipeline_llama into a separate file

---

torchtitan/float8.py
train.py

[fix] float8 should be applied on all model_parts

---

torchtitan/models/norms.py
train_configs/debug_model.toml
train_configs/llama2_13b.toml
train_configs/llama2_70b.toml
train_configs/llama2_7b.toml
train_configs/llama3_405b.toml
train_configs/llama3_70b.toml
train_configs/llama3_8b.toml

as titled, add warning to compile rmsnorm as it's not fully ready yet, i.e. this issue https://github.com/pytorch/torchtitan/issues/497
We can remove this warning once we fix the issue

Add warning to compile rmsnorm

---

README.md
docs/float8.md

add float8 link in README so we can redirect people from dev-discuss post to torchtitan repo
README looks like this after rendering
float8.md looks like this
I tried the command locally and traces are looking good

add float8 to README

---

torchtitan/parallelisms/parallelize_llama.py

* __->__ #508
This PR
- enables `inline_inbuilt_nn_modules` for block-level compilation
- removes `cache_size_limit` adjustment in async TP

address TODOs as 2D recompiles is fixed

---

estimation.py
torchtitan/parallelisms/__init__.py
torchtitan/parallelisms/parallelize_llama.py
torchtitan/parallelisms/pipeline_llama.py
torchtitan/parallelisms/pipelining_utils.py
train.py

* #512
* __->__ #510
This PR refactors the PP vs. non-PP setup in `train.py`:
- moves `build_pipeline_schedule ` into `pipeline_llama` which reduces the interface for PP in `train.py`
- refactors the set up flow, so that we only have two main if-else for PP vs. non-PP, one in setup phase, the other in training phase.
- I think it's already clear to read or copy-paste, and it's not necessary to create separate sub-functions to hold the code.
This PR also removes unnecessary module returns in `parallelize_llama`, as we are modifying module in-place. Note that torch.compile and AC require returning and reassigning the module. But since we are doing per-block compile and AC, we achieve that in-place for the whole …

[BE][5/n] simplify pp vs. non-pp set up

---

.ci/docker/requirements.txt
.github/workflows/integration_test_4gpu.yaml
.github/workflows/integration_test_8gpu.yaml
.github/workflows/unit_test_cpu.yaml
README.md

* __->__ #513
torchdata 0.8.0 is officially released (https://github.com/pytorch/data/releases), which contains the `StatefulDataLoader` we use.
We can remove the temporary nightly install.

depend on torchdata 0.8.0 instead of nightly

---

.ci/docker/requirements.txt
torchtitan/datasets/hf_datasets.py

* __->__ #521
The support of `skip` on "an `IterableDataset` obtained from `split_dataset_by_node`" has landed in https://github.com/huggingface/datasets/pull/6965 and released in https://github.com/huggingface/datasets/releases/tag/2.21.0
For previous discussions see
https://discuss.huggingface.co/t/skip-not-implemented-for-iterabledataset-after-split-dataset-by-node/91450
I manually did a unit-test on the c4 dataset (as an `IterableDataset`) by replacing https://github.com/pytorch/torchtitan/blob/main/test/datasets/test_checkpoint.py#L14

uniformly use skip for both (map-style) Dataset and IterableDataset

---

train.py

* __->__ #526
This is in line with the effort in #510, to make it easy to see the boundary between PP training vs. non-PP training.

keep pp vs. non-pp split

---

test_runner.py
torchtitan/config_manager.py
torchtitan/models/norms.py
train_configs/debug_model.toml

* __->__ #535
It seems this feature (#442) has been very unreliable, e.g.
- it did not work well with TP in terms of numerics, despite passing unit test (#506)
- it does not work with PP as expected (still having the cuda context error which `fused_rmsnorm` experienced)
- it used to work in 1D but seems to have no effect today (08/19), not sure why
Let's remove it for now. To get performant RMSNorm:
- apply (block-level) torch.compile, or
- use `fused_rmsnorm` in 1D or 2D (which also doesn't support PP well)
- wait for a dedicated CUDA kernel
This PR also adjusts integration tests as we now use `rmsnorm` as default.

remove compiled_rmsnorm

---

torchtitan/float8.py

closes: https://github.com/pytorch/torchtitan/issues/548
> Nvidia Ada Lovelace GPUs (e.g., RTX 4090, L20, L40) with SM89 version are also support FP8 MMA, and hence, it is recommended to relax the CUDA architecture limitations to enable FP8 training on a broader range of devices.
>
> and the [CUDA 12.0 announcement](https://developer.nvidia.com/blog/cuda-toolkit-12-0-released-for-general-availability/) says that it supports Lovelace architecture:
> '*CUDA 12.0 exposes programmable functionality for many features of the NVIDIA Hopper and NVIDIA Ada Lovelace architectures: ...32x Ultra xMMA (including FP8 and FP16)*'
> 
> - https://developer.nvidia.com/blog/cuda-toolkit-12-0-released-for-general-availability/
> - https://nvidia.github.io/TensorRT-LLM/reference/support-matrix.html
> - …

[MRG] relax the FP8 CUDA arch limitation to SM89

---

test_runner.py
torchtitan/config_manager.py
torchtitan/parallelisms/pipeline_llama.py
train.py

* __->__ #555
Discussed with @wconstab and @kwen2501 , it seems PP tracer has two limitations right now:
1. It doesn't support `init_weights`, thus requiring a seed checkpoint to do init, which is something we probably will deprecate soon after we have the init support for manual splitting.
2. It doesn't support mixed precision training, as the tracer requires that the model being traced be consistent with the model during forward.
We came to the conclusion to remove PP tracer for now, to have a clean version of torchtitan.

remove PP tracer

---

docs/performance.md

As title. We have updated the peak FLOPs for H100 so we need to use the correct number here

Fix the performance number for 405B

---

train_configs/llama3_405b.toml

Somehow, when rebasing, the legacy float8 enabling flag stays in the 405B toml. Let's remove it. And this does not affect the perf number we obtained because the old flag is just a no-op after rebase.

[ez] Remove legacy float8 enabling flag in 405B toml

---

test/test_fused_rms_norm.py

* __->__ #573
* #518
The import is not correct.

Fixes test_fused_rms_norm.py

---

README.md

* __->__ #574
1. adds DDP and HSDP to key features
2. removes outdated fixed nightly version -- we should always recommend the latest nightly, as it's guarded by CI
3. includes pointers to the float8 and async TP posts
4. other minor fixes

update README to include new features and remove outdated msg

---

torchtitan/parallelisms/pipeline_llama.py

* __->__ #588
Uses meta device for tensors/model used before pipeline splitting.
*Important:*
Relies on pytorch/pytorch#136243 to make PipelineStage avoid
materializing the model and the input/output buffers eagerly.
Relies on existing .to(device) in train.py to finally materialize the
model.

[PP] Fix PP meta init

---

torchtitan/checkpoint.py

This PR fixes the type hint of some classes in the checkpointing code.

chore: fixing type hint checkpointing class

---

torchtitan/checkpoint.py

* __->__ #602
Summary:
1. The original code does not utitlize `share_memory=True`, this may
cause incorrectness or slowdown.
2. The original code does not pass the correct cpu-offloaded state_dict,
which can cause another slowdown or incorrect saving.

Fix some zero-overhead checkpointing bugs

---

README.md
docs/memory_profiler.md

Add [memory_profiler](https://github.com/pytorch/torchtitan/pull/395) to README, explain how to use memory profiler with `--profiling.enable_memory_snapshot` and `--profiling.save_memory_snapshot_folder`

[BE][doc] add memory_profiler to README

---

docs/float8.md

explain why float8 needs to be distributed aware and how it's different to bfloat16

[BE][doc] explain why float8 needs to be distributed aware

---

torchtitan/datasets/tokenizer/__init__.py
torchtitan/parallelisms/parallel_dims.py

I was reading the framework just out of interest and found two quick fixes.
Especially, the rationale behind removing `strict=True` from `zip` is:
1. It's obvious that both iterables have the same length.
2. `strict=True` was introduced in `zip` in Python 3.10, but `pyproject.toml` specifies `requires-python >= 3.8`.

Two trivial fixes

---

test_runner.py

* __->__ #621
There is a test in CI that is using `ScheduleFlexibleInterleaved1F1B` which was removed in https://github.com/pytorch/pytorch/pull/137783. So removing that test to fix CI.
Separately I noticed we are not using the `pipeline_parallel_microbatches` config correctly, so i am looking into that

[PP] fix CI

---

docs/fsdp.md

Grad scaler is based on DTensor at FSDP2, its APIs [accept DTensor input](https://github.com/pytorch/pytorch/pull/132816) now

[BE][doc]Update fsdp readme, GradScaler enabled for FSDP2

---

torchtitan/utils.py

And a warning when the device name is not supported, to avoid confusions with misleading MFUs

Add H200 bf16 peak flops

---

docs/composability.md
torchtitan/config_manager.py
torchtitan/models/llama/model.py
train.py

* #643
* #645
* __->__ #642
cc: @tianyu-l I checked that TP=2, DP=4 with compile looks okay:
```
[rank0]:2024-10-22 08:04:37,873 - root - INFO - Training starts at step 1, with local batch size 1, global batch size 4, sequence length 8192, total steps 1000 (warmup 200)
[rank0]:/data/users/andgu/pytorch/torch/_inductor/lowering.py:1759: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager.
[rank0]:  warnings.warn(
[rank0]:/data/users/andgu/pytorch/torch/autograd/graph.py:825: UserWarning: cuDNN SDPA backward got grad_output.strides() != output.strides(), attempting to materialize a grad_output with matching strides... (Triggered internally at …
```

Move output `.float()` to loss fn and compile it if compiling

---

run_llama_train.sh

* __->__ #643
* #645
nice to default to this because users may not know to pass this env var
PyTorch will try to default in the future, but there are still some unsupported cases internally

Use expandable segments in `run_llama_train.sh`

---

torchtitan/checkpoint.py

Upstream PyTorch has a bug (pytorch/pytorch#138575) with `dcp.load()` that causes the objects pointed to by `state_dict` to diverge from the objects in use by the train loop. Specifically, torch is supposed to update in-place the Stateful elements in `state_dict`, however it also replaces the references in `state_dict` with the newly loaded object, resulting in the CheckpointManager instance having a stale trainstate/optimizer/etc.
This causes an issue when attempting to load a model from a checkpoint and subsequently save the checkpoint -- the loaded trainstate/optimizer/etc are saved instead of the current values. As a result, if a training run is pre-empted and resumed twice, the results are subtly wrong.
Until pytorch/pytorch#138575 is merged, this should work around the issue.
From …

Workaround for pytorch/pytorch#138575 distributed checkpoint loading bug

---

test/multimodal_model/test_multimodal_model.py
torchtitan/models/llama_multimodal/__init__.py
torchtitan/models/llama_multimodal/model.py

After https://github.com/pytorch/torchtitan/pull/589, we are adding decoder model to torchtitan with simple unit test.

[Multimodal model] Add the decoder of the multimodal model

---

estimation.py

Fixes
```python
2024-10-28 17:20:47,425 - root - INFO - Estimating memory usage...
2024-10-28 17:20:47,426 - root - INFO - Tensor parallelism and pipeline parallelism are not supported yet.
Traceback (most recent call last):
File "/home/ubuntu/carlos/torchtitan/estimation.py", line 219, in <module>
torch.distributed.destroy_process_group()
File "/home/ubuntu/.pyenv/versions/titan/lib/python3.10/site-packages/torch/distributed/distributed_c10d.py", line 2014, in destroy_process_group
assert pg is not None
AssertionError
```

Do not destroy if the world did not init

---

test_runner.py
torchtitan/config_manager.py
torchtitan/models/llama/model.py
torchtitan/parallelisms/parallelize_llama.py
torchtitan/utils.py
train.py

resolve #620 
Add config: `--training.enable_cpu_offload`
Command: `CONFIG_FILE="./train_configs/llama3_8b.toml" ./run_llama_train.sh`
For non-pp case:
For pp case:

Enable FSDP2 cpu offloading

---

torchtitan/config_manager.py

https://github.com/pytorch/torchtitan/blob/7310abea8782bbe459b662bc6d8411fe8d55f62c/torchtitan/parallelisms/parallel_dims.py#L35-L36 does not allow `data_parallel_replicate_degree` to be -1

Fix data_parallel_shard_degree description

---

torchtitan/parallelisms/parallelize_llama.py

* __->__ #666
**Summary**
https://github.com/pytorch/pytorch/pull/138945 fixes DeviceMesh access on flattened mesh which are constructed from more than 2 meshes. Refer to the fix PR for details if interested.
In #592 we avoided this issue by calling `_flatten` instead of direct accessing the flattened mesh. We want to turn back to mesh access which is more straightforward since the fix has been merged in PyTorch.

[BE] replace the extra DeviceMesh _flatten with mesh access

---

docs/checkpoint.md
scripts/convert_llama_to_dcp.py

Closes #305. 
Just wanted to get this out here quickly. 
The script is very simple since the weights are already in the completely correct format, names and everything. All of the complexity is avoided by not using HF, and so I believe that any functionality relating to HF should be located on their side. However, I do have a DCP -> HF export script which might be useful for some people, in case HF does not have/add one.
I'll be happy to add any needed documentation or tests.

Add script to convert pickled Llama weights to DCP

---

torchtitan/__init__.py
torchtitan/metrics.py
torchtitan/models/norms.py
torchtitan/utils.py
train.py

register for example:
```python
c10::register_privateuse1_backend("npu")
torch.utils.rename_privateuse1_backend("npu")
torch._register_device_module('npu', torch_npu.npu)
```
ussage:
"torch.cuda" should be replaced by "DEVICE_MODULE"
".cuda()" should be replaced by ".to(device=DEVICE_TYPE)"

support 3rd-party backend

---

torchtitan/config_manager.py
torchtitan/utils.py

resolve https://github.com/pytorch/torchtitan/issues/593
grad norms are quite different if running the same config twice
grad norms become exactly the same in repeated runs

ensure reproducible determinsitc numerics

---

torchtitan/float8.py

Summary:
The float8 delayed scaling configuration was broken for two reasons:
1. the enum value was compared to a string, which would always fail, leading to the amax syncing function to never be called. Fixing by comparing to the right enum value.
2. the `enable_pre_and_post_forward` was set to False, which meant that the initialization path was taken at every iteration, preventing us from ever seeing performance benefits compared to dynamic scaling.
This PR fixes both of the issues above. Note that this fix requires https://github.com/pytorch/ao/pull/1341 to work correctly.
Note that delayed scaling is still not faster than dynamic due to some missing features in inductor, but this PR at least sets us up with a good baseline.
Test Plan:
```
// dynamic scaling on LLaMa 3 8B (baseline)
// …
```

fix float8 delayed scaling configuration

---

.ci/docker/ubuntu/Dockerfile
.github/workflows/integration_test_4gpu.yaml
.github/workflows/integration_test_8gpu.yaml

* __->__ #718
Pytorch stopped releasing cu121 nightlies.

Migrate CI to CUDA 12.4

---

docs/checkpoint.md
torchtitan/config_manager.py
train.py

Fixes https://github.com/pytorch/torchtitan/issues/662
followed @fegin advice to test this and indeed things are working https://gist.github.com/msaroufim/2925b3f17b631bf370a49f185b6e169d
```
[checkpoint]
enable_checkpoint = true
folder = "checkpoint"
interval_type = "steps"
interval = 10
model_weights_only = false
export_dtype = "float32"
async_mode = "disabled" # ["disabled", "async", "async_with_pinned_mem"]
load_step = 10
```

Add checkpoint load step

---

torchtitan/parallelisms/parallelize_llama.py

The tp_enabled parameter was not being used within the apply_fsdp function. 
Removing it simplifies the function signature while maintaining all existing functionality.

remove unused `tp_enabled` parameter from `apply_fsdp`

---

torchtitan/parallelisms/parallel_dims.py
torchtitan/utils.py

* #684
* #685
* __->__ #720
**Summary**
This PR improves the design of DeviceMesh hierarchy in torchtitan. Now, we define all device meshes except `world_mesh` into 2 categories:
1. Basic mesh: those meshes defined in job `.toml` file by users. This include `pp` (`pipeline_parallel_degree`), `dp_replicate` (`data_parallel_replicate_degree`), `dp_shard` (`data_parallel_shard_degree`), `tp` (`tensor_parallel_degree`), and `cp`(`context_parallel_degree`).
2. Synthesized mesh (or called "derived mesh"): meshes that are synthesized from basic mesh by `_flatten()`. If the mesh in synthesized from a single mesh, then it is equivalent to aliasing. So far we utilize 2 synthesized meshes: `dp` and `dp_shard_cp`. The `dp` …

[DP] change device mesh dim naming convention to make it more consistent

---

README.md
docs/checkpoint.md
docs/converging.md
docs/datasets.md
docs/debugging.md
docs/metrics.md
torchtitan/metrics.py
torchtitan/parallelisms/parallel_dims.py
torchtitan/profiling.py

* __->__ #729
1. move Flight Recording and memory profiling docs to `debugging.md`
2. unify heading & subheading style across docs
3. simplify `parallel_dims.py` assertions
4. other misc changes

some cleanups on docs and parallel_dims

---

test_runner.py
torchtitan/config_manager.py
torchtitan/utils.py
train.py

* __->__ #728
**Summary**
https://github.com/pytorch/pytorch/pull/142093 adds a new API that allows user to choose a rotater method for RingAttention between "allgather" and "alltoall". This PR adds a new config in torchtitan for this feature along with test covering it.
**Test**
CI

[cp] add option to choose kv shards rotation method

---

train.py

The initializations in `init_weights` can create gradients. This is almost always not intended
The alternative would be to add the decorator to `model.init_weights` directly. Then the responsibility is moved to the model writer. I can change that if that's preferred.

Run init_weights under no_grad

---

train.py

* __->__ #755
TBD: I'll create a pytorch issue with ways to repro errors

turning off compile on loss function

---

torchtitan/config_manager.py

Here is a PR to make it *a bit easier* to observe the configuration across different experiments. This is generally useful for MLOps to observe the exact configuration of your training run.
For example, this makes it easier for a user to extend the code and log the config in Weights & Biases:
```
wandb.init(config=job_config.to_dict())
```

Accessible config as dict

---

torchtitan/checkpoint.py
torchtitan/optimizer.py

Combine `state_dict` and `load_state_dict` from OptimizerWrapper to OptimizerContainer so that we only have one optimzier related class
Also, add `get_lr_scheduler_state` to SchedulersContainer when update `lr_scheduler` at self.state

[BE] Combine OptimizerWrapper and OptimizerContainer

---

README.md
scripts/estimate/estimation.py
tests/integration_tests.py
torchtitan/config_manager.py
torchtitan/parallelisms/parallelize_llama.py
train.py
train_configs/debug_model.toml

* __->__ #759
1. having "store_true" and "default=True" makes it impossible to disable a config (e.g. color printing from cmd line). It seems there are no easy ways other than changing the "enable" to "disable".
2. add an option to print all the args, which would be helpful if we run things on cluster and want to see what configs we used
3. add a link in README to PP post

[BE] improve argparser

---

scripts/estimate/estimation.py
tests/integration_tests.py
torchtitan/parallelisms/parallel_dims.py
torchtitan/parallelisms/parallelize_llama.py
train.py

* __->__ #761
This PR
1. fixes the loss all-reduce mesh from `dp_replicate + dp_shard`, to `dp_replicate + dp_shard + cp`, by creating a new submesh named by `"dp_cp"`
2. removes the restriction on running `dp_replicate` + `cp` with `dp_shard=1`, as it's just HSDP with the FSDP part being CP only; also added a test of this case
3. fixes the estimation.py parallelism condition checking, as it only works with HSDP and FSDP

fix loss with CP enabled

---

CONTRIBUTING.md
README.md

* __->__ #762
This PR adds a few badges and does some overall updating & restructuring of README.

mild README revamp

---

torchtitan/utils.py

* __->__ #769
to address https://github.com/pytorch/torchtitan/issues/766

early all-reduce total_norm in non-PP grad norm clipping

---

torchtitan/parallelisms/pipeline_llama.py
torchtitan/parallelisms/pipelining_utils.py

* __->__ #781
PP is using the `pipeline_parallel_degree` as the default number of microbatches when it should be `pipeline_parallel_degree * len(stages)` for multi-stage schedules. 
Also fixed up some logging / added logging.

fix num_microbatches input for PP

---

tests/integration_tests.py

* #784
* __->__ #783
The integration tests do not output to terminal unless the process exits, which is a problem I hit when I had a hanging test and there was no output.
Due to setting `stdout=subprocess.PIPE`, this captures the standard output of the subprocess. The output is only printed after the process exits. If we dont set stdout `stdout=None`, then standard output is not captured; it is inherited from the parent process which is just the terminal and prints out normally.

Stream subprocess stdout

---

torchtitan/parallelisms/pipelining_utils.py

* __->__ #784
* #783
For PP, the batch size should be divisible by number of microbatches so we should fail early if this is not the case

Add validation that batch size is divisible by number of microbatches

---

torchtitan/utils.py
train.py

Fixes https://github.com/pytorch/torchtitan/issues/763

Do not aggregate the losses since last log step

---

tests/integration_tests.py
torchtitan/optimizer.py

Optimizer-in-backward would free gradients memory during backward, causing integration test failure with pp at gradient scale
Disable test with pp first, would enable later with support to multi schedule pp
Add test with dp, tp, cp, hsdp

Disable integration test between optimizer-in-backward and pp

---

scripts/estimate/estimation.py
torchtitan/config_manager.py
torchtitan/float8.py
train.py

Torchao plans to deprecate delayed scaling, delete it at torchtitan
Fix the issue: https://github.com/pytorch/torchtitan/issues/654
Here are the logs running with `enable_float8_linear = true`
1. `compile = false`
```
[rank0]:2025-01-31 10:12:50,551 - root - INFO - Float8 training active
[rank0]:2025-01-31 10:12:50,571 - root - INFO - Swapped to Float8Linear layers with enable_fsdp_float8_all_gather=False
[rank0]:2025-01-31 10:12:50,572 - root - INFO - Model llama3 8B size: 8,030,261,248 total parameters
[rank0]:2025-01-31 10:12:50,572 - root - INFO - Applied selective activation checkpointing to the model
[rank0]:2025-01-31 10:12:50,635 - root - INFO - Applied FSDP to the model
[rank0]:2025-01-31 10:12:50,835 - root - INFO - CUDA memory usage for model: 3.77GiB(3.97%)
[rank0]:2025-01-31 …
```

Delete delayed scaling

---

torchtitan/checkpoint.py
torchtitan/optimizer.py

Currently, lr_scheduler is stored differently as optimizer, model and data_loader, with keys to be "lr_scheduler_0", "lr_scheduler_1", ... stored in the state
This PR aims to flatten lr_shceduler so that all the schedulers would be stored as a list of state_dict under self.state['lr_scheduler'], which is consistent with optimizer
Here we have the assumption that all the optimziers have the same lr_scheduler, thus only to save a single lr_scheduler's state_dict and load it to all the schedulers works here.
The lr_scheduler has the state_dict like:
`{'base_lrs': [0.0003], 'last_epoch': 1, 'verbose': False, '_step_count': 2, '_get_lr_called_within_step': False, '_last_lr': [2.985074626865671e-06], 'lr_lambdas': [{}]}`
The PR is tested by 2 parts:
1. test lr_scheduler value before and after …

[BE] Lr schduler flatten

---

torchtitan/parallelisms/parallelize_llama.py

This fixes a bug in how per op AC interacts with float8 training. The bug surfaced through unexpected increase in peak memory usage when integrating row-wise scaling into float8 training in https://github.com/pytorch/torchtitan/pull/808. The full RCA can be in found in this thread starting [here](https://github.com/pytorch/torchtitan/pull/808#issuecomment-2625944668).
- I [tested](https://github.com/pytorch/torchtitan/pull/808#issuecomment-2631411213) different model layers and permutations of configurations and found the minimal repro was a FFN with per op AC + FSDP + compile + float8 row-wise scaling.
- I [analyzed](https://github.com/pytorch/torchtitan/pull/808#issuecomment-2632563586) the triton kernels generated for the compiled FFN forward pass in bf16 vs fp8, tracking peak …

Remove abs from save list for per op AC to fix bug causing unexpected increase in peak memory usage for float8 training with row-wise scaling

---

tests/integration_tests.py
torchtitan/parallelisms/pipeline_llama.py
train.py

This is dependent on the changes in this pytorch stack: https://github.com/pytorch/pytorch/pull/146217
Add support for running `ZBVZeroBubbleSchedule` and v-shaped CSV schedules in torchtitan
Fixes https://github.com/pytorch/torchtitan/issues/774

Support ZBVZeroBubbleSchedule

---

torchtitan/checkpoint.py
torchtitan/utils.py

We disable auto gc and manually perform GC every 50 steps. This can cause issues when checkpointing frequence is smaller than GC frequency.
This PR change checkpoint manager to call GC when a save or load happens.

Do GC collect after dcp.save and dcp.load

---

torchtitan/datasets/hf_datasets.py

Fix issue https://github.com/pytorch/torchtitan/issues/809
The current `self._data.skip(self._sample_idx)` could not get the correct data for c_4 dataset.
Thus we switch to next() first before the fix is landed.
Test plan:
We reproduce the https://github.com/pytorch/torchtitan/issues/809 by resuming from checkpoint at step 500, then compare the loss curve in 3 conditions:
1. the origin curve running from step 0 to 750
2. the resumed curve keeping .skip()
3. the resumed curve switch to next(), with this PR change
Warning
for c_4 dataset, if we resume from a large enough step, we call next() for `self._sample_idx` times, resuming from checkpoint would be much slower than using .skip()
Next step:
add unit test:
1. test the state_dict check between dcp.save/load and torch.save/load
2. test …

Avoid using skip() in hf_datasets

---

scripts/estimate/estimation.py
scripts/generate/test_generate.py
tests/unit_tests/test_dataset_checkpointing.py
tests/unit_tests/test_train_spec.py
torchtitan/dataloader.py
torchtitan/datasets/__init__.py
torchtitan/datasets/hf_datasets.py
torchtitan/datasets/tokenizer/__init__.py
torchtitan/models/__init__.py
torchtitan/models/llama/__init__.py
torchtitan/train_spec.py
train.py

Allow users to customize dataloader

---

torchtitan/utils.py

Some PyTorch backends cannot support torch.uint64, so we cast seed_tensor to cpu tensor to avoid using torch.uint64 for privateuse1 backends.

Workaround for backends that don't support torch.uint64

---

torchtitan/metrics.py

In [wandb docs](https://docs.wandb.ai/ref/python/log/), the `step` is taken as a keyword arg once logging.  
It would be better to pass the current step as an arg of `wandb.log` rather than a metric.

[Wandb] Properly log steps in wandb

---

torchtitan/train_spec.py
torchtitan/utils.py

Hi, thanks for sharing this great repo.
I just have some small fixes while working on my fork that I think would make sense to send back here as 
1. Make the Embedding parameters count more robust. We now use the same looping logic `p.numel() for p in model.parameters()` as above, instead of accessing the module's weight directly. It would help if models have nested Embedding modules for trainable and frozen embeddings.
2.Fix typing issue in the ModelProtocol where from_model_args should be a classmethod and takes cls as fist arg, since we will return the model via cls(model_args).

2 small fixes: more robust Embedding params count & ModelProtocol typing issue.

---

.github/ISSUE_TEMPLATE/bug.yml
.github/ISSUE_TEMPLATE/config.yml
docs/converging.md

* __->__ #856
https://github.com/pytorch/torchtitan/pull/855 landing failed due to "status check not passed", relanding in this new PR.

add an issue template for bug report

---

torchtitan/logging.py

* __->__ #860
As title, Sometimes, we have logs from different modules and components. Adding a prefix will give us a way to grep titan related logs.

Add a prefix to titan logs

---

scripts/estimate/estimation.py
tests/unit_tests/test_train_spec.py
torchtitan/loss.py
torchtitan/models/llama/__init__.py
torchtitan/models/llama/model.py
torchtitan/train_spec.py
train.py

Allowing for more flexibility in the training by adapting the loss function (e.g. label smoothing, auxilary loss term, ...).

Adding `loss_fn` to `TrainSpec` model datastructure.

---

torchtitan/metrics.py

The logging directory path was set up but the directory was not created.
In the  case of Wandb Logger, this caused the following:
```
[rank0]:wandb: WARNING Path ./outputs/tb/20250220-1829/wandb/ wasn't writable, using system temp directory.
```
With this addition, the wandb logging is properly set to ``` ./outputs/tb/20250220-1829/wandb```

Create logging directory in wandb logger

---

tests/integration_tests.py
torchtitan/components/optimizer.py
torchtitan/config_manager.py

Currently Titan does not use Fused AdamW as default.
This PR makes Fused the new default.
After investigating current parallelisms using Llama 8B, I found an average speedup of 2.64% as follows:
<google-sheets-html-origin>
Fused AdamW | FSDP, eager | 2.24%
-- | -- | --
8B | FSDP, compile | 1.63%
  | TP | 3.62%
  | AsyncTP | 3.26%
  | CP | 2.97%
(debug model)  | PP | 2.10%
  |   |  
Gains | Average | 2.64%
  | Min | 1.63%
  | Max | 3.62%
Updated to add --optimizer.implementation with ["for-loop", "foreach" and "fused"] support.
Testing:
beyond verifying no issues with all parallelisms above, verified that fused/foreach/ for-loop is being set with the new default config:
~~~
[rank0]:Using foreach implementation for optimizer
[rank0]:foreach=True, fused=False
~~~
~~~
[rank0]:Using for-loop …

use Fused AdamW as default

---

tests/unit_tests/test_train_spec.py
torchtitan/components/optimizer.py

Passing `optimizer_cls` to `OptimizersContainer` and `OptimizersInBackwardContainer` constructors, instead of `name`.

Generalize Optimizers container type, by passing base internal optimizer class.

---

README.md

Summary:
Seems like we need to install the module after the latest codebase refactors, updating the README.md to match since this is BC breaking.
Test Plan:
```
with-proxy CONFIG_FILE="./torchtitan/models/llama/train_configs/debug_model.toml" ./run_train.sh
```
Reviewers:
Subscribers:
Tasks:
Tags:

update README.md with up-to-date installation instructions

---

tests/integration_tests.py

PyTorch trunk has an offensive PR that breaks CP. It is better to get tests signals from other parallelisms than no signals.

Temporarily disable CP tests

---

docs/float8.md
torchtitan/components/float8.py
torchtitan/config_manager.py
torchtitan/models/llama/parallelize_llama.py

Summary:
Exposes the float8 config from recipe name API from torchao, so we can use it to easily configure float8 with rowwise scaling from torchtitan.
Usage:
```
with-proxy CONFIG_FILE="./torchtitan/models/llama/train_configs/llama3_8b.toml" ./run_train.sh \
--model.converters float8 \
--training.compile \
--float8.recipe_name rowwise
```
Example, pretraining LLaMa 3 8B on 8 H100s:
```
// baseline (bf16 + compile)
> with-proxy CONFIG_FILE="./torchtitan/models/llama/train_configs/llama3_8b.toml" ./run_train.sh --training.compile
...
step: 20  loss:  8.4931  memory: 47.65GiB(50.16%)  tps: 5,760  mfu: 33.73%
// experiment (rowwise float8 + compile)
> with-proxy CONFIG_FILE="./torchtitan/models/llama/train_configs/llama3_8b.toml" ./run_train.sh --model.converters float8 --training.compile …
```

add configuration for float8 with rowwise scaling, via recipe lookup

---

torchtitan/config_manager.py
torchtitan/protocols/model_converter.py

Summary:
I want to do this literally every time I use float8 in titan, let's make it reusable!
```
with-proxy CONFIG_FILE="./torchtitan/models/llama/train_configs/debug_model.toml" ./run_train.sh --model.converters float8 --model.print_after_conversion
```
Test Plan:
Reviewers:
Subscribers:
Tasks:
Tags:

QOL: add CLI option to print model after conversion to stdout

---

torchtitan/tools/utils.py

This PR enhances the method for counting embedding layers, making it more versatile and compatible with various model architectures, especially in HF-format.
Replace the Llama-specific embedding count:
```py
num_params -= sum(p.numel() for p in model.tok_embeddings.parameters())
```
by a more generic way
```py
num_params -= sum(
sum(p.numel() for p in m.parameters())
for m in model.children() if isinstance(m, nn.Embedding)
)
```

Exclude embedding params by module class

---

torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/symm_mem_recipes/triton_on_device_all_to_all_v.py

This PR treats PP and EP as the two most important model parallel degrees of DeepSeek.
When creating the model on each rank, the rank's PP and EP info are recognized, and we only create the relevant parts.
That is, we employ this flavor of model creation:
```
with mesh:
model = DeepseekV3Model(model_args)
```
where `mesh` carries the model parallel information.
This is similar to how `torchchat` creates "model chunks" in case of PP.
Test:
`$ torchrun --standalone --nproc-per-node 4 model.py`

Add pipeline parallel to DeepSeek

---

pyproject.toml

Either we require python>=3.10, or we delete TypeAlias imports in the 2 occurrences present in the code base.

require python>=3.10

---

torchtitan/experiments/deepseek_v3/checkpoint.py
torchtitan/experiments/deepseek_v3/download.py
torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/model_config.py
torchtitan/experiments/deepseek_v3/run.py

Enable loading weights from HF checkpoint.
1. Download
- Added `download.py` to allow user download a HF checkpoint into local disk cache.
- Usage: `python download.py {model_id}`
2. Load weights
- Added `checkpoint.py` to load tensors from HF cache dir into a model.
- The model can be a model chunk or full model.
3. Various code refactor
- Moved `ModelArgs` into a separate file, adding DeepSeek config registry
4. Added support for DeepSeek-V2
- Greedy routing
- Softmax score function
5. Added example run.py based on [DeepSeek-V2-Lite](https://huggingface.co/deepseek-ai/DeepSeek-V2-Lite/tree/main), a 16B toy MoE.
`torchrun --standalone --nproc-per-node 4 run.py`

[DeepSeek] Enable checkpoint load from HF

---

tests/integration_tests.py

* __->__ #912
This PR undo https://github.com/pytorch/torchtitan/pull/898 and re-enables CP tests in CI as https://github.com/pytorch/pytorch/pull/148125 fixed the DTensor sdp flash attention op.
CI

re-enable CP tests since DTensor scaled dot product flash attention has been fixed

---

torchtitan/components/checkpoint.py

Removed redundant initialization of variables in `checkpoint.py`.
You can check the code at:  
https://github.com/pytorch/torchtitan/blob/main/torchtitan/components/checkpoint.py#L299-L309
```python
self.staging = False
self.sending_to_checkpoint_mp = False
self.staging_id = None
self.cpu_offload_state_dict = None
self.staging_stream = torch.cuda.Stream() if self.enable_staging else None
self.staging = False
self.sending_to_checkpoint_mp = False
self.staging_id = None
self.cpu_offload_state_dict = None
self.staging_stream = torch.cuda.Stream() if self.enable_staging else None
```
```python
self.staging = False
self.sending_to_checkpoint_mp = False
self.staging_id = None
self.cpu_offload_state_dict = None
self.staging_stream = torch.cuda.Stream() if self.enable_staging else None
```

 Remove duplicate variable initialization in `checkpoint.py`

---

torchtitan/components/checkpoint.py

Hi, thanks for sharing this great repo.
I just have a small fix while working on my fork that I think would make sense to send back here as:
The `_states_to_load` function expects an integer as input, but the `load` function passes `checkpoint_id` (a string/path-type value) when invoking it. As a result, `_states_to_load` returns **all states** (including the model, optimizer, dataloader, etc.). Since the dataloader's state contains `dp_rank`, and the seed checkpoint was created with `world_size` fixed to 1, errors occur during training when loading this seed checkpoint in a multi-machine environment (where `world_size > 1`). This inconsistency in distributed training parameters triggers compatibility issues.
```python
def _states_to_load(self, step: int) -> Dict[str, Any]:
"""Determines …
```

[fix] fix bug in loading seed checkpoint

---

torchtitan/components/optimizer.py
torchtitan/config_manager.py
torchtitan/models/llama/train_configs/debug_model.toml
torchtitan/models/llama/train_configs/llama3_405b.toml
torchtitan/models/llama/train_configs/llama3_70b.toml
torchtitan/models/llama/train_configs/llama3_8b.toml

Add an option into `torchtitan/components/optimizer.py` and config files to allow users to control the epsilon value passed into the optimizer.
Some papers suggest that providing users with the flexibility to control the epsilon value is important. This ensures that epsilon does not dominate the updates when gradients become extremely small. The default value of $1^{-8}$ may not always be sufficiently small; in some cases, setting epsilon to $1^{-15}$ or even zero could be more appropriate.
See https://arxiv.org/pdf/2412.17743 and https://arxiv.org/abs/2309.14322 for more details.

[Optim] Add an option controlling the optimizer eps

---

torchtitan/tools/utils.py

replaces MI250 with MI250X, fixes the peak FLOPS value (since MI250X is a dual-chip GPU, FLOPS should be calculated per GCD).

fix MI250X peak FLOPS

---

torchtitan/tools/metrics.py

Not all devices have all metrics.

Replacing  device_info[key] with device_info.get() .

---

docs/fsdp.md

* people asks about the FSDP2 equivalance of no_sync, that's `set_requires_gradient_sync`
* ignored_params is recently implemented. people start using it already. update the doc

[FSDP2][doc] highlight set_requires_gradient_sync and ignored_params

---

torchtitan/models/llama/train_configs/debug_model.toml
torchtitan/tools/metrics.py
torchtitan/train.py

This is similar in spirit to [PR_944](https://github.com/pytorch/torchtitan/pull/944) (cc @lkhphuc)  but takes a slightly different approach.
Problem - users that default turn on PP training will get -1 for their loss.  This is b/c by default, rank 0 is the only one logged.
However, for *most* PP schedules, the loss is output on the last rank.
Thus, users see -1 for loss and it's a bad/confusing experience.
This PR adds a check to review both the current PP schedule (b/c for VBlocks, loss is returned on 0) and if it is a last rank loss schedule, then it checks that the first rank of the last stage is visible in the LOG_RANK environment variable.
If not, it warns the user, using Red for the warning if color is enabled, and highlights the rank they should add in yellow:
Note that I …

[PP] Ensure loss is visible on console for users

---

.github/workflows/lint.yaml

The tags in tj-actions/changed-files action are compromised and are leaking GitHub secrets in repos using the compromised repo. This pins the action to a known good hash.
https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised

Tags in tj-actions/changed-files are compromised

---

torchtitan/models/llama_multimodal/model.py
torchtitan/models/norms.py

1. Switch RMSNorm implementation to native PyTorch version
2. Remove torchtitan local RMSNorm implementation
Test by training llama_8b model after switching to native nn.RMSNorm  (training.seed = 0, deterministic=true):
- Before the change:  memory: 49.58GiB(52.20%)  tps: 5,233
- After the change:  memory: 49.66GiB(52.28%)  tps: 5,173
Test by training llama_8b model after switching to native nn.RMSNorm  (training.seed = 0, deterministic=true): 
- Loss:
- Before the change: blue line
- After the change:  orange line
- The blue line and orange line is not exactly identical. From @tianyu-l 's comment: Before the change, the downcast from FP32 to BF16 happens before the final output * self.weight whereas in pytorch kernel, the downcast happens after the final matmul .
Test by training …

Switch RMSNorm implementation to native PyTorch version

---

torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/run.py
torchtitan/experiments/deepseek_v3/symm_mem_recipes/triton_on_device_all_to_all_v.py

* #956
* #989
* #958
* #954
* #952
* __->__ #941
This PR contains three changes:
1. all-to-all-v kernel writes out `output_splits` instead of total received
(so that we can use the split info as `input_splits` in the second shuffle or backward)
2. Add backward for all_to_all_v (WIP)
3. Move parts of the model out of `no_grad()`
ghstack-source-id: 8e0dda40b4dc9206343a020c42e8cd8c5741f860
Pull Request resolved: https://github.com/pytorch/torchtitan/pull/941
Test
```
$ torchrun --standalone --nproc-per-node 4 run.py
...
logits: torch.Size([2, 128, 102400])
logits: torch.Size([2, 128, 102400])
loss=tensor(510.3908, device='cuda:2', grad_fn=<MeanBackward0>)
loss=tensor(506.3376, device='cuda:3', …
```

[DeepSeek] all-to-all-v kernel writes out `output_splits`

---

torchtitan/experiments/deepseek_v3/model.py

* #956
* #989
* #958
* #954
* __->__ #952
* #941
Previously the model code re-arranges the received tokens so that those for the same expert reside in a contiguous space.  It leads to complex code and the need of argsort.
This PR uses the `y[expert_idx == i] = expert(tokens[expert_idx == i])` style to perform expert processing.
It provides a simpler alternative (at least in coding style) as if the tokens are processed in place.

[DeepSeek] Simplify token grouping before expert processing

---

tests/integration_tests.py
torchtitan/config_manager.py
torchtitan/models/llama/model.py
torchtitan/models/llama/parallelize_llama.py
torchtitan/train.py

Summary: This PR enables using FlexAttention for llama model.
Differential Revision: D70186496
SDPA
```
[rank2]:[titan] 2025-03-20 00:15:44,653 - root - INFO - step: 20  loss:  8.4828  memory: 36.06GiB(45.56%)  tps: 2,546  tflops: 147.44  mfu: 47.26%
```
FlexAttention
```
[rank0]:[titan] 2025-03-20 00:38:14,024 - root - INFO - step: 20  loss:  8.4238  memory: 36.06GiB(45.56%)  tps: 2,168  tflops: 125.53  mfu: 40.23%
```
FlexAttention + max auto tune without cuda graph
```
[rank0]:[titan] 2025-03-20 00:33:37,008 - root - INFO - step: 20  loss:  8.5293  memory: 36.75GiB(46.43%)  tps: 2,421  tflops: 140.20  mfu: 44.94%
```

Enable FlexAttention for llama model

---

torchtitan/models/llama/parallelize_llama.py

Part of #866
- This PR fixes async TP for bf16 and float8 w/ tensorwise scales.
- Support for async TP + float8 w/ rowwise scales requires a different change in pytorch here https://github.com/pytorch/pytorch/pull/149247
Saving reduces scatter op in per op SAC was breaking the graph pattern matching used implement part of async TP, causing it to "fail silently" - async TP would fail to identify subgraphs to replace with `fused_scaled_mm_reduce_scatter` but continue to run using vanilla TP anyway, unbeknownst to the user.
See root cause analysis here https://github.com/pytorch/torchtitan/issues/866#issuecomment-2725779000
- Confirmed via manual testing with torchtitan + inspecting compile graphs, that the fusion is occurring correctly for bf16 and float8 w/ tensorwise scales.
- Investigate …

[Async TP] Don't save reduce scatter output for per op SAC

---

torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/run.py

Reland #989
Adding dist.all_to_all_single as token shuffle method.
This is made the default option for better support of backward pass.
The alternative shuffle method --on_device_all_to_all_v -- will be enabled only when user calls
model.setup_symm_mem()
and is limited to inference only.

[DeepSeek] Add all_to_all_single impl; Enable backward

---

torchtitan/experiments/deepseek_v3/run.py

Reland #956
This PR adds FSDP on the Expert modules. Since before this we are already doing a DP-to-EP shuffle between the Attention and the Experts, we applies HSDP on the Attention, with the replicate dimension being the same as the EP dimension.
In particular, we are using Zero-2 sharding which shards optimizer and gradients, and not sharding the weights, to avoid the expensive re-gather of MoE.

[DeepSeek] Enable data parallel

---

torchtitan/experiments/__init__.py
torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/__init__.py
torchtitan/experiments/simple_fsdp/model.py
torchtitan/experiments/simple_fsdp/parallelize_llama.py
torchtitan/experiments/simple_fsdp/simple_fsdp.py
torchtitan/experiments/simple_fsdp/tests/__init__.py
torchtitan/experiments/simple_fsdp/tests/test_numerics.py

This PR adds front-end code of SimpleFSDP and integrated with TorchTitan's training. 
| Feature | Support |
| :--------: | :--------: |
|Meta Initialization| ✅ |
|Activation Checkpointing| ✅ |
|Mixed Precision Training| 🚧 |
|Tensor Parallelism| 🚧 |
|Context Parallelism| ✅ |
|Pipeline Parallelism| ✅ |
|Distributed Checkpointing|  🚧 |
|Float8 Training| ❌| 
The loss curves are all benchmarked with `training.mixed_precision_param = float32` (SimpleFSDP's MPT integration is on-going) and `training.seed = 42` on 4 GPU.
- Fully Shard Mode (['dp_shard'], [4]): FSDP2 and SimpleFSDP's losses are perfectly matched
- Replicate Mode (['dp_replicate'], [4]): FSDP2 and SimpleFSDP's losses are almost the same.
**Note that the FSDP optimizations (reordering and bucketing) are not included. Thus, users …

[SimpleFSDP] Front-end Code and Unit test

---

.github/workflows/integration_test_8gpu.yaml
README.md
docs/checkpoint.md
run_train.sh
scripts/estimate/run_memory_estimation.sh
scripts/generate/README.md
scripts/generate/run_llama_generate.sh

Running `python` or `torchrun` with `-m` option helps resolve package structure without the need to do `pip install -e`.
This is suggested by @yzhangcs in https://github.com/pytorch/torchtitan/issues/897#issuecomment-2744951051
> It avoids the potential pitfalls of using `pip install -e .`, which can sometimes lead to inconvenient and hard-to-debug issues, especially when we're making frequent changes to the codebase.

use -m option to run scripts as modules

---

docs/checkpoint.md
torchtitan/components/loss.py
torchtitan/models/llama/__init__.py

Noticed that in the memory snapshot when running the Llama3-8B models, the cross entropy loss is causing huge spikes in peak memory: 
Replace the cross entropy loss function with a chunked version can help reduce peak memory by 7GiB without affecting training throughput. This is inspired by the torchtune [implementation](https://github.com/pytorch/torchtune/blob/c3703482bde72e572b535d3f7c43c81e94164ebc/torchtune/modules/loss/ce_chunked_output_loss.py#L13).
**Baseline run**
```
...
[rank0]:[titan] 2025-03-20 08:19:11,539 - root - INFO - step: 30  loss:  7.7158  memory: 49.58GiB(52.20%)  tps: 5,966  tflops: 345.53  mfu: 34.94%
[rank0]:[titan] 2025-03-20 08:19:25,291 - root - INFO - step: 40  loss:  7.3677  memory: 49.58GiB(52.20%)  tps: 5,957  tflops: 345.01  mfu: 34.88%
[rank0]:[titan] …
```

chunked cross entropy loss to reduce peak memory

---

torchtitan/tools/utils.py

Adding support to calculate bf16 peak flops for Intel's GPU `Data Center GPU Max 1550` also known as `Ponte Vecchio (PVC)`.

[XPU] bf16 peak flops for Intel's Data Center GPU Max 1550

---

torchtitan/experiments/deepseek_v3/generate.py
torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/run.py
torchtitan/experiments/deepseek_v3/symm_mem_recipes/__init__.py
torchtitan/experiments/deepseek_v3/symm_mem_recipes/triton_on_device_all_to_all_v.py

A couple changes compared to previous try in #941:
- Make `OnDeviceAllToAllV` in functional form (easier to form autograd graph).
- Move symm-mem based splits buffer inside `OnDeviceAllToAllV` (this part does not need gradients). This would introduce a small copy from normal split tensor to this symm-mem backed split tensor, but since this copy is very small (of `ep_size`), so we should be able to tolerate it, and reduce outside dependency.
- Create different symm mem space for data buffers of different micro-batches (from pipeline parallel), because autograd does not allow them to step on each other's toes.
Test:
`torchrun --standalone --nproc-per-node 8 run.py`
Using traditional `torch_all_to_all`:
```
loss=tensor(681.1560, device='cuda:4', grad_fn=<MeanBackward0>)
loss=tensor(681.1560, …
```

[DeepSeek] Re-enable backward for on-device all_to_all_v

---

torchtitan/experiments/deepseek_v3/model.py

Removes the `numpy` usage and `tolist` CUDA sync when computing `gatherd_idxs`.

[DeepSeek] remove numpy, avoid tolist in gatherd_idxs

---

torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/parallelize_llama.py

I observed that
1. When CP is used without other data parallel (`dp_replicate` / `dp_shard`), it works fine with and without torch.compile
2. When CP is combined with any other data parallel, it only works without torch.compile. It would fail under compile, with error info like "_UnboundLocalError: cannot access local variable 'buf899' where it is not associated with a value_"
So I'm marking CP as "to be fixed".

fix simple_fsdp logic when CP is used

---

torchtitan/components/lr_scheduler.py

When `decay_steps=0`, a ZeroDivisionError occurs.
Example:
Given parameters:
- decay_steps=0
- warmup_steps=5
- training_steps=10
Then:
- warmup_stable_steps=warmup_steps+stable_steps=10
- current_step ranges from 1 to 10
With the original code, when `current_step` equals `warmup_stable_steps`, we fall through to the `else` branch, which triggers a ZeroDivisionError due to `decay_steps` being 0.
```python
if current_step < warmup_steps:
current_step += 1
curr_adjustment = float(current_step / (warmup_steps + 1))
elif current_step < warmup_stable_steps:
curr_adjustment = 1.0
else:
progress = float(current_step - warmup_stable_steps) / decay_steps
if lr_decay_type == "linear":
curr_adjustment = 1 - progress
elif lr_decay_type == "sqrt":
curr_adjustment = 1 - math.sqrt(progress)
elif …
```

Fix ZeroDivisionError when decay_steps=0

---

torchtitan/experiments/simple_fsdp/README.md

This is following up on https://github.com/pytorch/torchtitan/pull/1011
Previously CP didn't work on my end because I was accidentally using an old version of pytorch, which had a mismatch to triton version. It works for me now.
I'll add CI later.

fix simple fsdp readme

---

run_train.sh

This PR ensures that the current logging environment is visible inside of titan.  This way checks like PP logging visible can operate successfully by matching the logged ranks are also valid for showing the PP loss.
Testing:
a - run with 1F1B without valid loss rank (4 in this case), verify warning fires
b - run with 1F1B with valid loss rank, ensure no warning displayed
c - run with one and multiple ranks, verify export has no effect on actual rank logging (same as before).

ensure logging ranks are visible to titan

---

torchtitan/distributed/utils.py
torchtitan/train.py

This pull request splits the `Trainer.__init__()` method to separate necessary initializations from actions that require an initialized trainer. The main() function now handles these actions, which currently include seed checkpoint creation and training step.
This modification resolves the current seed checkpoint failure and enables the implementation of future actions that are not part of the training process.

Avoid perform trainer.train() for seed checkpoint creation case

---

torchtitan/components/dataloader.py

Currently there is no provision to provide a custom collate function to the dataloader in torchtitan. This PR aims to address that.
For example, if users are having multimodal datasets, they might want to collate the data in a specific way. They can't use the provided `build_hf_dataloader` function from `hf_dataset.py` today  because the `ParallelAwareDataloader` class inside it does not take a `collate_fn` parameter. 
We can solve this by simply accepting a `collate_fn` parameter in the `__init__` of the `ParallelAwareDataloader` class. This class is inheriting from `StatefulDataLoader` where the collate function is already supported! All that we have to do is to accept this parameter and pass it while calling the init of the base class from ParallelAwareDataloader.
An example usage …

Adding support for collate_fn parameter in ParallelAwareDataloader class

---

torchtitan/train.py

I noticed this log line when running a torchtitan training run, which seemed to indicate a missing f-string:
`Training starts at step {self.step + 1}.`
I took a look at the code and it does seem to be a case of accidentally using a string literal instead of f-string, so I fixed it.

Fix missing f-string in logging

---

torchtitan/train.py

Fixed a bug where the `Trainer.train` method was incorrectly using `trainer` instead of `self`.
When `train.py` is executed and the `if __name__ == "__main__": ...` block runs, the global variable `trainer` is identical to `self`, so execution proceeds without issues.
However, when we import and run `Trainer` from other files, the `trainer` variable doesn't exist, causing an error. This PR fixes that issue.

Correct self reference in Trainer

---

scripts/estimate/estimation.py
tests/unit_tests/test_train_spec.py
torchtitan/components/loss.py
torchtitan/experiments/multimodal/__init__.py
torchtitan/experiments/simple_fsdp/__init__.py
torchtitan/models/llama/__init__.py
torchtitan/protocols/train_spec.py
torchtitan/train.py

To enable chunked loss, I refactor the `train_spec.loss_fn` to `train_spec.build_loss_fn` as suggested in #996
Also:
- Unified chunked loss implementation with the `cross_entropy_loss` name, since default is a special case with chunk=1.
Identical loss and memory:
- Enable compiling the loss function as it's working fine for me, and result in reduction of memory and slightly better througput.
While we only have one type of loss, I create a field for `loss.name` with default to 'cross_entropy' to be fork-friendly anyway.

refactor train_spec.loss_fn to build_loss_fn & chunked loss

---

torchtitan/experiments/kernels/triton_mg_group_gemm/simple_MoE.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/mg_grouped_gemm.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/tma_autotuning.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/unit_test_forwards.py

Previously the output dimension is `n*G`, but we want only `n`.
Also added alignment requirement for the grouped input, i.e. each element in `m_sizes` must be divisible by the alignment size.
The impl today has alignment of 64, which is a bit big. We should drive it down. (TODO @lessw2020 )

[GroupGemm] Fix output dimension of M*G kernel

---

torchtitan/components/checkpoint.py
torchtitan/components/dataloader.py
torchtitan/components/float8.py
torchtitan/components/ft.py
torchtitan/components/loss.py
torchtitan/components/lr_scheduler.py
torchtitan/components/metrics.py
torchtitan/components/optimizer.py
torchtitan/components/tokenizer.py
torchtitan/datasets/hf_datasets.py
torchtitan/datasets/tokenizer/tiktoken.py
torchtitan/distributed/parallel_dims.py
torchtitan/distributed/utils.py
torchtitan/models/llama/pipeline_llama.py
torchtitan/protocols/train_spec.py

My LSP (based)pyright gives lots of error about signatures mismatches so I tried to fix them up.
Before:
After:
The only linter error left is at the pipelining function, where currently it is declared to take "BaseModelArgs", but the actual passed in value is of subtype "TransformerModelArgs" etc. I haven't found a clean way to declare it yet.
- Also fixes some other inconsistences in return type, redundant nested if etc.
- Also since the pyproject.toml requires python >=3.10, I also upgrades other typing to be more modern such as "Dict -> dict" etc.
The fixes are not exhaustive and I can followup more in this PR or another PR if you like.
But if it conflicts with some Meta's internal tool etc, feel free to close.

improve TrainSpec and general typing

---

torchtitan/experiments/deepseek_v3/generate.py
torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/deepseek_v3/run.py

Integrating the M*G Group GEMM kernel by @lessw2020 in #967. This kernel requires tokens for the same expert to reside together. So we need to permute the received tokens before the GEMM.
We also need to make sure each token group's length (i.e. `m_sizes`) meet the alignment requirement of the Group GEMM. This requires padding some unused index (like `-1`) into the permutation indices.
With this integration, we remove a few CPU sync points in the original program, for example, getting the `received` length, and slicing the chunk of tokens for each expert.
And most obviously, we removed the for loop needed to perform matmul for all local experts.
The generation of permutation indices are in CPU right now. We should write a kernel for it.
```
$ torchrun --standalone --nproc-per-node 4 …
```

[DeepSeek] Integrate M*G Group Gemm

---

tests/integration_tests.py
torchtitan/config_manager.py
torchtitan/models/attention.py
torchtitan/models/llama/model.py
torchtitan/models/llama/parallelize_llama.py

This PR adds support of block causal/document mask. We currently only add this feature for FlexAttention.

Supports block causal mask

---

tests/unit_tests/test_dataset_checkpointing.py
torchtitan/datasets/hf_datasets.py
torchtitan/protocols/train_spec.py
torchtitan/train.py

1. Change `inputs` from `Tensor` to `dict[str, Tensor]`, which could support multiple inputs. The default dictionary key is "input" if there's only one item in the dict.
2. Change  Dataloader ouptuts to match the new format
If a model has multiple input Tensor, rewrite `train_step()` function in trainer to handle multiple inputs.
Tested on training with Llama 8b model

Change the function signature in trainer to support flexible inputs 

---

.github/workflows/integration_test_8gpu.yaml
README.md

It seems pytorch nightly no longer supports cu124
see https://download.pytorch.org/whl/nightly/torch/

update CI to use pytorch nightly

---

torchtitan/experiments/deepseek_v3/indices.py
torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/__init__.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/mg_grouped_gemm.py
torchtitan/experiments/kernels/triton_mg_group_gemm/torchao_pr/tma_autotuning.py

Added `generate_permute_indices` in indices.py which executes the following on GPU (previous it was done on CPU, but involves a GPU-CPU sync).
Prepare permutation indices and the number of tokens for each expert.  The
permutation indices are the indices of the tokens for each expert.  The
number of tokens for each expert is the sum of the number of tokens for
such experts from all ranks. This number is aligned to the provided
alignment requirement (usually comes from group gemm).
Test:
`python indices.py`

[DeepSeek] Move permutation index generation to GPU

---

torchtitan/components/float8.py
torchtitan/config_manager.py
torchtitan/models/llama/train_configs/llama3_405b.toml
torchtitan/models/llama/train_configs/llama3_70b.toml
torchtitan/models/llama/train_configs/llama3_8b.toml

Fixes #1043 
- Adds `--float8.filter_fqns` argument, which accepts a comma-separated list of FQNs. Defaults to empty list.
- When float8 training is enabled, any nn.Linear which has dim sizes divisible by 16 and whose FQN does not appear in the `filter_fqns` list, will be module-swapped for a Float8Linear layer.
- Manual testing the following cases:
- Single FQN via command line: `--float8.filter_fqns "output"` - [logged module definition](https://www.internalfb.com/phabricator/paste/view/P1778127918)
- Multiple FQNs via command line: `--float8.filter_fqns "output,attention.wq"` - [logged module defintion](https://www.internalfb.com/phabricator/paste/view/P1778128848)
- Single FQN via toml ("output"): [logged module defintion](https://www.internalfb.com/phabricator/paste/view/P1778129382) …

[float8] Make module filter function for float8 training configurable

---

torchtitan/experiments/deepseek_v3/generate.py
torchtitan/experiments/deepseek_v3/model.py

Added CUDA Graph support for inference, see method `generate_with_cuda_graph`.
Included a minor change to the model so that the `cos_sin_cache` of `RotaryEmbedding` is setup at model init time rather than model run time.

[DeepSeek] Add CUDA Graph support

---

.gitignore
torchtitan/experiments/flux/README.md
torchtitan/experiments/flux/model/autoencoder.py
torchtitan/experiments/flux/scripts/download_autoencoder.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml

1. Modify `load_ae()` function signature to use pre-downloaded auto-encoder. 
2. Add script to download autoencoder before training.
3. Add instructions in README.md to fix #1067 
Train flux debug model on a single GPU with refreshed pycache.

[Flux] Add script to download autoencoder before training 

---

torchtitan/distributed/utils.py

as I'm seeing the following warning
```
Warning: TORCH_NCCL_AVOID_RECORD_STREAMS is the default now, this environment variable is thus deprecated. (function operator())
```
from https://github.com/pytorch/pytorch/blob/main/torch/csrc/distributed/c10d/ProcessGroupNCCL.cpp#L997

remove TORCH_NCCL_AVOID_RECORD_STREAMS env var setting

---

torchtitan/experiments/deepseek_v3/moe_kernels.py
torchtitan/experiments/deepseek_v3/unit_testing/permute_indices_testing.py

This PR updates the original Triton kernel in indices.py (https://github.com/pytorch/torchtitan/pull/1062) to move it to a more parallelized and vectorized implementation to better support larger runs.  
This provides roughly an 8.7x perf improvement for 256 experts. 
This kernel functionally achieves the same as before:
Prepare permutation indices and the number of tokens for each expert with any required alignment, where alignment is driven by the group gemm requirement. 
* The permutation indices are the indices of the tokens for each expert. 
* The number of tokens for each expert is the sum of the number of tokens for
such experts from all ranks. 
However, this kernel improves the parallelization by assigning one block to each expert, and threads in each block process the tokens in …

[DeepSeek][Kernels] add on device, parallelized permute_indices kernel

---

torchtitan/components/float8.py
torchtitan/experiments/llama4/model/args.py
torchtitan/experiments/llama4/model/moe.py
torchtitan/tools/utils.py

as titled
also fixing a breakage caused by https://github.com/pytorch/torchtitan/pull/1086

[llama4] fall back to for-loop based MoE if not on SM90 or later

---

torchtitan/experiments/flux/parallelize_flux.py

As title. Set reshard_after_forward=False for last layer to avoid gather right after reshard. Similar to llama as discussed in #1091.

[Flux] Improve reshare_after_forward for Flux model's last layer

---

torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/simple_fsdp.py

This PR adds mixed precision training support for SimpleFSDP, together with this change from PyTorch: https://github.com/pytorch/pytorch/pull/150740. 
**(This is a placeholder for now, and shall be merged only after the PyTorch pr is landed.)** 
The loss curves are all benchmarked with `training.seed = 42` on 4 GPUs.
- Fully Shard Mode (['dp_shard'], [4]): FSDP2 and SimpleFSDP's losses are perfectly matched
- Hybrid Shard Mode (['dp_replicate', 'dp_shard'], [2, 2]): FSDP2 and SimpleFSDP's losses are similar
The end-to-end SimpleFSDP mixed precision training integration has been proved to work properly in the PR from this fork: https://github.com/tianyu-l/pytorch_intern24/pull/20.

[SimpleFSDP] Add mixed precision training support

---

torchtitan/experiments/kernels/moe/indices.py
torchtitan/experiments/kernels/moe/unit_tests/permute_indices_testing.py
torchtitan/experiments/llama4/model/moe.py

This PR updates both llama4 and DeepSeekv3 to use the faster parallelized kernel for generate_permute_indices. 
This also adds a unit test for the core kernel in generate_permute_indices.
~~~
Summary for fixed total experts (256), where we mimic various DeepSeek experts across a number of ranks:
Ranks | Experts/Rank | Original (ms) | Optimized (ms) | Block Size | Speedup | Correct
------------------------------------------------------------------------------------------
1 |          256 |        0.241 |        0.020 |        128 |   11.95x |       1
4 |           64 |        0.222 |        0.020 |        128 |   10.97x |       1
16 |           16 |        0.221 |        0.021 |        128 |   10.40x |       1
32 |            8 |        0.224 |        0.025 |         64 |    8.81x | …

upgrade generate_permute_indices with faster kernel (parallelized)

---

torchtitan/config_manager.py
torchtitan/distributed/pipeline.py
torchtitan/experiments/llama4/__init__.py
torchtitan/models/llama3/__init__.py
torchtitan/models/llama3/pipeline_llama.py

This PR continues the work laid out in https://github.com/pytorch/torchtitan/pull/1041#pullrequestreview-2748308167
There are two cases in the PP auto-split algorithm:
1. `num_layers_per_virtual_stage` is given. In this case, we now require rigid fit of the effective layers (regular layers + weighted input + weighted output) onto pipeline stages and ranks, with several assertions. It is the users' responsibility to figure out the input weight, output weight, and the number of regular layers, so that they can be arranged nicely.
2. `num_layers_per_virtual_stage` is not given. In this case, we by default set each pipeline rank to have 2 virtual stages, and try to distribute all effective layers evenly onto the PP stages. If there are extra layers, we disperse them in the starting stages. …

refactor PP auto-split algorithm

---

torchtitan/experiments/flux/model/layers.py
torchtitan/experiments/flux/model/model.py
torchtitan/experiments/flux/tests/test_generate_image.py
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml

Implement `init_weights()` function in `model.py`. Adopted from DiT: https://github.com/facebookresearch/DiT/blob/main/models.py#L125
Train flux-schnell model on 8 H100 GPU
```
[rank0]:[titan] 2025-04-10 13:51:04,539 - root - INFO - Synchronizing and adjusting timeout for all ProcessGroups to 0:01:40
[rank0]:[titan] 2025-04-10 13:52:24,633 - root - INFO - step: 10  loss:  1.9750  memory: 78.43GiB(82.56%)  tps: 88,370  tflops: 0.00  mfu: 0.00%
[rank0]:[titan] 2025-04-10 13:53:52,970 - root - INFO - step: 20  loss:  2.3648  memory: 78.43GiB(82.56%)  tps: 89,026  tflops: 0.00  mfu: 0.00%
[rank0]:[titan] 2025-04-10 13:55:21,283 - root - INFO - step: 30  loss:  2.3314  memory: 78.43GiB(82.56%)  tps: 89,052  tflops: 0.00  mfu: 0.00%
[rank0]:[titan] 2025-04-10 13:56:49,486 - root - INFO - step: …
```

[Flux] Implement Initialize weight function for Flux model

---

torchtitan/train.py

This is a short term solution for #1056 (pytorch core issue tracker: https://github.com/pytorch/pytorch/issues/150859)
For a long term solution, the compiler folks are looking into supporting deterministic recompute of intermediates for AC during the backward pass.
- Manual testing confirmed loss decreases as expected without NaNs (training logs: https://www.internalfb.com/phabricator/paste/view/P1787321079
cc @tianyu-l @lessw2020

[float8] emulate eager mode precision casts for float8 rowwise

---

tests/integration_tests.py
torchtitan/config_manager.py
torchtitan/experiments/llama4/__init__.py
torchtitan/experiments/llama4/infra/parallelize_llama.py
torchtitan/experiments/llama4/model/args.py
torchtitan/experiments/llama4/train_configs/debug_model.toml
torchtitan/models/llama3/__init__.py
torchtitan/models/llama3/model.py
torchtitan/models/llama3/parallelize_llama.py

There are conflicts between JobConfig and ModelArgs. Specfically, if we let ModelArgs arguments be in JobConfig, then users have to control these arguments via toml files or command line arguments. However, for some flext_attn configurations, the requirement doesn't make sense as some models have the desired settings. 
This PR removes these configurations from JobConfig and uses model flavor to control whether flex_attn should be enabled or not.

Remove flex_attn configs from JobConfig

---

torchtitan/experiments/llama4/README.md
torchtitan/experiments/llama4/infra/parallelize_llama.py
torchtitan/experiments/llama4/model/args.py
torchtitan/experiments/llama4/model/model.py
torchtitan/experiments/llama4/model/moe.py
torchtitan/models/llama3/model.py
torchtitan/models/llama3/parallelize_llama.py

There are two issues in this solution:
1. Communication (sync tokens per expert across all DP ranks) happens on the default stream. Maybe need to arrange it on FSDP/DDP comm stream.
2. The communication is blocking experts bias update, thus always exposed.
We need to evaluate if 2 is a problem to performance. 1 is OK if 2 is acceptable.

[llama4] add auxiliary-loss-free load balancing to MoE token routing

---

torchtitan/experiments/deepseek_v3/model.py

This PR corrects a last minute change in the sort_tokens function.  
moe_on_device was updated to reflect it but moe_forward was missing the change. 
Note - I missed this b/c I only ran testing for inference.  
Ran training loop to verify this is fully working.

[DeepSeek] update moe_forward to sort_tokens api update

---

torchtitan/distributed/utils.py

Recently introduced 'extra_pg' in distributed utils does not provide a default. 
Set default to None like the underlying `dist_reduce`.
This is to avoid breaking forks that currently uses `dist_mean` or `dist_max`.

dist_utils: set extra process group default to None

---

torchtitan/components/metrics.py
torchtitan/train.py

Just to make the trainer's init a little bit more general and fork friendly.
In our fork, the metrics processor would need some information from the specific model args as well.

add model_args as argument to build_metrics_processor_fn in train.py

---

torchtitan/experiments/flux/flux_argparser.py
torchtitan/experiments/flux/model/model.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml

1. Refactor Flux arg parser to follow #767 new argparse practice
2. Explicitly change dtype for flux model to avoid #1137 (when FSDP is not enabled)
3. Fix txt_in layer shape issue by changing the config of schnell and dev model #1146 
Without FSDP (fsdp dim = 1) :
- Encoder's dtype = float32, Flux model's dtype = float32
With FSDP enabled:
- Encoder's dtype = bfloat16, Text and Image encodings' dtype=bfloat16
- Flux Model's dtype: sharded params are in fp32, reduce-scatter is in fp32, so gradient updates happen in fp32. dtype when calculation=bfloat16
cc @CarlosGomes98

[Flux] Refactor argparser to follow new practice, Fix dtype and txt_in layer shape issue

---

torchtitan/experiments/deepseek_v3/generate.py
torchtitan/experiments/deepseek_v3/group_gemms.py
torchtitan/experiments/deepseek_v3/model.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/cg_backward.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/cg_forward.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/cg_reference.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/debug.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/tma_cuda_autotune.py
torchtitan/experiments/kernels/triton_contiguous_group_gemm/unit_test_cg.py

This PR adds a triton based contiguous group gemm and integrates it with deepseek. 
This group gemm has full backwards support. 
Testing:
a - have verified cg group gemm works for deepseek inference. 
b - have added and run unit tests for both forward and backward. (The perf test is against manual looping).
~~~
===== Testing Backward Pass: DeepSeek Shapes   =====
Testing shape: M=512, K=128, N=128, group_size=128
Testing shape: M=1,024, K=1,024, N=1,024, group_size=128
.
===== Testing Forward Pass: DeepSeek Shapes =====
Testing shape: M=4,096, K=1,024, N=1,024, group_size=128
Testing shape: M=4,096, K=4,096, N=4,096, group_size=128
Testing shape: M=2,048, K=4,096, N=7,168, group_size=128
Testing shape: M=2,048, K=7,168, N=2,048, group_size=128
.
===== Benchmarking Backward Pass with …

[Kernels] add triton contiguous groupgemm

---

tests/unit_tests/test_job_config.py
torchtitan/config_manager.py

The `MergedJobConfig` class doesn't have method to_dict(), so when the job_config is an instance of `MergeJobConfig`, we will run into the following error when running with `--job.print_args`.
```
AttributeError: 'MergedJobConfig' object has no attribute 'to_dict'
```

Fix MergedJobConfig class to enable printing arguments during training

---

torchtitan/components/metrics.py

Log JobConfig so it show up in WandB Config section like this:

Wandb: log JobConfig to Config

---

torchtitan/experiments/flux/dataset/flux_dataset.py

Previously, `random` is using different random number generator as `torch`, and we initialized torch random seed using `set_determinisitc` at the beginning of training. 
Change to use torch rng to keep deterministic between runs, which could help further debugging.

[Flux] Deterministic algorithm of data preprocessing for Flux

---

torchtitan/experiments/llama4/train_configs/debug_model.toml

this PR updates the debug_toml for llama4 as we no longer need to use Adam for group gemm.
The core issue regarding hangs with group gemm was resolved already (https://github.com/pytorch/torchtitan/pull/1166). 
Thus, we can remove the todo and go back to AdamW as default. 
Testing:
verified 1K run with AdamW works as expected, no hangs as before.

update llama4 debug_model to use group gemm with AdamW again

---

docs/debugging.md
torchtitan/config_manager.py

Updated parser treats booleans as 'actions' by default. Updated docs to reflect this change + included entry point for print/stdout of config values for debugging
re #1176

Document behavior of booleans for parser

---

torchtitan/__init__.py
torchtitan/components/float8.py
torchtitan/components/mx.py
torchtitan/config_manager.py

Stacked PRs:
* #1196
* __->__#1190
--- --- ---
Add mxfp8 path
```Shell
with-proxy CONFIG_FILE="torchtitan/models/llama3/train_configs/llama3_8b.toml " ./run_train.sh --model.print_after_conversion --training.compile --training.steps 50 --model.converters mx --mx.recipe_name "mxfp8"
```
I wish we could do Polls in PRs  but bike shed all the names and whether we should add a separate configmanger from float8 section and JobConfig entry
As well here is a version that encodes all of it into recipe name: https://github.com/pytorch/torchtitan/pull/1189
Logs:
``` Shell
[rank0]:/home/drisspg/.conda/envs/nightly/lib/python3.12/site-packages/torch/_inductor/lowering.py:1881: UserWarning: Torchinductor does not support code generation for complex operators. Performance may be worse than eager. …
```

Add mxfp8 path

---

torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/parallelize_llama.py
torchtitan/experiments/simple_fsdp/simple_fsdp.py

This PR adds tensor parallel (TP) support for SimpleFSDP, together with [this pr](https://github.com/pytorch/pytorch/pull/152286) from PyTorch.
**(This is a placeholder for now, and shall be merged only after the PyTorch pr is landed.)**
**Profile Trace & Convergence on debug model:**
The loss curves are all benchmarked with `training.seed = 42` on 4 GPUs.
The end-to-end SimpleFSDP TP integration has been proved to work in the PR from this fork: https://github.com/tianyu-l/pytorch_intern24/pull/25. Per the discussion with Tianyu, the new PyTorch PR has add `_StridedShard` following FSDP2 to be compatible with distributed checkpointing. The newly benchmarked results demonstrated it works properly.

[SimpleFSDP] Add tensor parallel support

---

torchtitan/experiments/flux/parallelize_flux.py

- Currently we did not enable CP for flux model training, so we need to remove the 
- For FSDP/ HSDP,  the correct dimension name should be ("dp_replicate", "dp_shard") or ("dp_shard",)

[Flux] Fix parallel dimension names 

---

torchtitan/experiments/flux/README.md
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/parallelize_flux.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml

1. Change flux-dev / flux-schnell model training to be ~30000 step based on current MAST training results
2. Enable checkpointing. We enabled final_layer reshard_after_forward to solve issue described [here](https://github.com/pytorch/torchtitan/pull/1167#discussion_r2075967381)
If we run following 2 runs, the training loss curve should be identical with `deterministic = True`:
1. Without checkpoint save and load, total step=10
2. Save checkpoint at step 5, and load checkpoint at step 5, continue training
Currently issue #1194 makes the training loss not strictly identical. To exclude the influence of #1194, we reset the seeds (by calling `set_deterministic()` at the beginning of step 6. Then the checkpoint save/load makes the training loss identical.

[Flux] Enable checkpointing

---

tests/unit_tests/test_model_converter.py
torchtitan/__init__.py
torchtitan/components/quantization/__init__.py
torchtitan/components/quantization/float8.py
torchtitan/components/quantization/mx.py
torchtitan/components/quantization/utils.py
torchtitan/config_manager.py

This PR
1. puts `float8.py` and `mx.py` under a `components/quantization` subfolder
2. extract the `module_filter_fn` into a `utils.py` file
3. fix typing of `filter_fqns: list[str] | str` to be just `list[str]`
4. some other cleanups

refactor quantization modules

---

torchtitan/tools/utils.py

This PR:
adds B200 BF16 throughput spec so that MFU can be calc'ed correctly on Blackwell B200.
data is from: https://nvdam.widen.net/s/wwnsxrhm2w/blackwell-datasheet-3384703
Testing:
verify on B200 that we go from 200% MFU b/c it falls back to A100 peak, to correctly using B200 4.5 Pflops and  12% MFU.

add B200 BF16 throughput spec for MFU

---

torchtitan/tools/utils.py

This PR:
adds L40s as a valid gpu type for get_peak_flops in order to properly calculate MFU. We are currently using L40's for some FT work.

add L40s gpu type for MFU calcs

---

torchtitan/train.py

Hey Folks!
I've had a really good time playing with torchtitan so far :) 
Looking into the code, as it stands, the way the data loader is wrapped by `next_batch` is not very pythonic. It makes it very awkward to iterate through the data loader in a pythonic way with `for` or `while`.
This is a PoC of my suggestion to make this more pythonic.
I think this will especially bear fruit in situations where we might want to iterate through a dataset from beginning to end, e.g., for a validation dataset.
To note, this current change might break a few of the models under experimental, which would need to mirror this change in their `train.py`

[Feature] Pythonify next_batch

---

torchtitan/experiments/flux/README.md
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml

Previously we specify `model.final_layer.reshard_after_forward()` to ensure the model weights are sharded the same way for checkpointing saving. But this requires FluxTrainer has knowledge about the model FSDP plan.
To decouple the model FSDP plan and the Flux trainer, change to check each module if it's FSDPModule.

[Flux] Decouple parallelism plan with trainer by resharding after evaluation

---

torchtitan/components/optimizer.py
torchtitan/train.py

Missed that we were using the ftOptimizer when doing fault tolerant communication for HSDP, we should skip this when we have semi-sync training enabled and only do quorum when the replica groups sync.

[ft] Skip extra quorum when using semi-sync training

---

torchtitan/experiments/deepseek_v3/train.py

this PR fixes (or at least works around) this issue (https://github.com/pytorch/torchtitan/issues/1224) that has suddenly appeared regarding duplicate gpu mapping and blocking deepseek with expert parallel training.  
This was previously not an issue but has popped up seemingly with the latest NCCL.  
Regardless, change is to ensure we run torch.cuda.set_device before initializing the device mesh. 
That restores deepseek training to as before. 
Testing:
deepseek training now working via train.py vs broken with duplicate gpu error.

[deepseek] fix/avoid Expert Parallel device mesh and 'duplicate gpu mapping' error

---

.ci/docker/requirements.txt
.github/workflows/integration_test_8gpu.yaml
.github/workflows/unit_test_cpu.yaml
docs/float8.md
tests/integration_tests.py
tests/unit_tests/test_model_converter.py
torchtitan/components/quantization/float8.py
torchtitan/config_manager.py

Add [emulate](https://github.com/pytorch/ao/blob/554cb60c750e6ef31bbcafec74bb76a4578902da/torchao/float8/config.py#L193) in float8, to enable test on older hardware.
Change relative warnings
Test result:
Test locally on 8 H100 server.
`CONFIG_FILE="./torchtitan/models/llama3/train_configs/llama3_8b.toml" ./run_train.sh --model.converters="float8" --float8.enable_fsdp_float8_all_gather --float8.precompute_float8_dynamic_scale_for_fsdp --float8.force_recompute_fp8_weight_in_bwd`
`CONFIG_FILE="./torchtitan/models/llama3/train_configs/llama3_8b.toml" ./run_train.sh --model.converters="float8" --float8.enable_fsdp_float8_all_gather --float8.precompute_float8_dynamic_scale_for_fsdp --float8.force_recompute_fp8_weight_in_bwd --float8.emulate`

Add emulate in float8 and relative checks

---

tests/integration_tests.py

As titled, this PR fixes the incorrect test name in CI testing per this previous discussion: https://github.com/pytorch/torchtitan/pull/1231#discussion_r2114360445

Correct CI test name

---

.github/workflows/integration_test_8gpu_simple_fsdp.yaml
torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/tests/integration_tests.py

This PR adds CI for SimpleFSDP. It mainly adopted FSDP-related integration tests from this file: https://github.com/pytorch/torchtitan/blob/main/tests/integration_tests.py
A few things to list here:
- Currently, DDP/HSDP + TP (SimpleFSDP's `replicate` and `hybrid_shard` mode) is not supported. I'll add support for them in follow-up PRs.
- DCP + SimpleFSDP failed in `test_generate` test on my end. The output seems to indicate some of the model weights are not correctly checkpointed when resharding from [dp:4] -> [tp:4]. [dp:4] -> [dp:2, tp:2] works out.
```
[rank2]:   File "/home/ruisi/pytorch/torch/distributed/checkpoint/default_planner.py", line 471, in create_default_local_load_plan
[rank2]:     raise RuntimeError(f"Missing key in checkpoint state_dict: {fqn}.")
[rank2]: RuntimeError: …
```

[SimpleFSDP] Add CI for SimpleFSDP

---

tests/unit_tests/test_job_config.py
torchtitan/config_manager.py

This PR:
Ensures that JobConfig extension values are included in the final merged JobConfig, rather than just the custom fields and their values all (incorrectly) set to zero. 
Fix has gone from closure to a one line adjustment (credit @tianyu-l )
Unit testing has been increased to verify and catch any future breaks like this (credit @jaysonfrancis )
Testing - verified all unit tests passing (with added assert for custom field update) and expert parallel extension use case working. 
Example:
~~~
@dataclass
class Parallelism:
expert_parallel_degree: int = 2
""" degree to parallelize experts """
~~~
results in 
~~~
parallelism=MergedParallelism(... expert_parallel_degree=0)
~~~
which is not what is desired. 
With PR:
~~~
parallelism=MergedParallelism(... expert_parallel_degree=2)
~~~

[Extensions] ensure extension default values from extension toml are used, not base class 

---

torchtitan/experiments/deepseek_v3/tokenizers/hf_tokenizer.py
torchtitan/experiments/deepseek_v3/train_ds_real.py

This PR adds an additional function in the hf_tokenizer file, remove_notset_root_handlers. 
This eliminates the duplicate logging that otherwise happens when importing HF's AutoTokenizer and avoids touching the titan.logging code per my earlier PR.  
without PR - when running ds, we can see two root level loggers are present (vs only one is present if you run from titan main which does not use HF tokenizers):
~~~
ROOT LOGGER HANDLERS
[rank0]:------------------------------
[rank0]:Handler 1:
[rank0]:    Type: StreamHandler
[rank0]:    Level: NOTSET (0)
[rank0]:    Stream: <stderr>
[rank0]:    Formatter:
[rank0]:      Format: %(levelname)s:%(name)s:%(message)s
[rank0]:      Date Format: None
[rank0]:      Style: <logging.PercentStyle object at 0x7fca6eaabdd0>
[rank0]:    Filters: None …

[deepseek] remove unset root logger from HF AutoTokenizer to avoid dupe logging

---

torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/job_config.py
torchtitan/experiments/flux/tests/test_generate_image.py
torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml

In the SD3 paper, independently drop each tokenzier's result for classifier free guidance in trainnig.
> For unconditional diffusion guidance (Ho & Salimans, 2022), we set the outputs of each of the three text encoders independently to zero with a probability of 46.4%, such that we roughly train an unconditional model in 10% of all steps.
Thanks @tianyu-l  for identifying this issue!

[FLUX] independently drop t5 and clip tokens for classifier free guidance 

---

.github/CODEOWNERS

As we discussed offline, set up a coder owner for the main components in TorchTitan, to ensure the code stability and provide light-weight protection. Next step is to set "protected branches" rule to require >= 1 code owner approval. 
Exclude experiment folder from code owner mechanism for fast iteration.

[BE] Set up Code owners for main components and exclude experiment folder 

---

docs/converging.md
scripts/estimate/estimation.py
tests/integration_tests.py
tests/unit_tests/test_dataset_checkpointing.py
torchtitan/components/dataloader.py
torchtitan/components/loss.py
torchtitan/components/metrics.py
torchtitan/config_manager.py
torchtitan/datasets/hf_datasets.py
torchtitan/distributed/pipeline.py
torchtitan/experiments/deepseek_v3/train_configs/deepseek_v2.toml
torchtitan/experiments/deepseek_v3/train_ds_real.py
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml
torchtitan/experiments/llama4/train_configs/debug_model.toml
torchtitan/experiments/llama4/train_configs/llama4_17bx128e.toml
torchtitan/experiments/llama4/train_configs/llama4_17bx16e.toml
torchtitan/experiments/multimodal/check_padding_mm.py
torchtitan/experiments/multimodal/mm_dataset.py
torchtitan/models/llama3/train_configs/debug_model.toml
torchtitan/models/llama3/train_configs/llama3_405b.toml
torchtitan/models/llama3/train_configs/llama3_70b.toml
torchtitan/models/llama3/train_configs/llama3_8b.toml
torchtitan/train.py

First, the batched backward calculation is refactored into its own function. Then, gradient accumulation is implemented by moving the data iterator inside the `train_step` method and consuming data from it as necessary. I added some extra handling for non-infinite data iterators, but if you dislike that additional complexity, I can remove it to simplify the code.
The feature is enabled by giving an additional `--training.global_batch_size`, which has a sensible default of 1 gradient accumulation step (i.e., no actual accumulation).
@tianyu-l thanks for the ping.

Support gradient accumulation

---

README.md
torchtitan/experiments/flux/train.py
torchtitan/train.py

After #1238 landed, we could consolidate FLUX train_step() to reuse the main trainer's `train_step` function, by removing the `eval_step()`.
We will replace eval_step() to be a `Validator` in the future to perform various validation methods.

Move eval to main train loop and consolidate FLUX train_step

---

torchtitan/experiments/llama4/model/moe.py

https://github.com/pytorch/torchtitan/pull/1254 removes the `max_len` param from `generate_permute_indices` but does not update the llama4 model.
cc @tianyu-l

[llama4] fix: remove max_len from generate_permute_indices

---

.github/workflows/integration_test_8gpu.yaml
.github/workflows/integration_test_8gpu_h100.yaml
.github/workflows/unit_test_cpu.yaml

According to https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#example-including-paths
> When all the path names match patterns in paths-ignore, the workflow will not run.
> If any path names do not match patterns in paths-ignore, even if some path names match the patterns, the workflow will run.

run core tests only if core files are modified

---

.github/workflows/release.yml

This is following
https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-pypi
An environment "release" has been created.
Will follow https://github.com/pytorch/torchtitan/issues/688 as the release process.

set up action to publish to PyPI on release

---

torchtitan/experiments/simple_fsdp/README.md
torchtitan/experiments/simple_fsdp/simple_fsdp.py
torchtitan/experiments/simple_fsdp/tests/integration_tests.py

As titled, this pr adds support for SimpleFSDP's DCP composability. The code is based on previous implementations from @fmassa @awgu @yf225 
The following losses match perfectly. The checkpoints are loaded from step-110.
(1) [dp:4] --> [dp:4]
(2) [dp:2, tp:2] --> [dp:2, tp:2] & [dp:2, pp:2]

[SimpleFSDP] Add support for SimpleFSDP DCP

---

docs/checkpoint.md

As title
From the test: https://github.com/pytorch/torchtitan/blob/main/tests/unit_tests/test_job_config.py#L123
- Commandline supports comma-seprated string,
- TOML file only support TOML native syntax for `list[str]`: `exclude_from_loading = ["optimizer", "lr_scheduler", "dataloader"]`

Fix checkpointing docs: Loading a comma-seprated string from toml file is off

---

README.md
benchmarks/README.md
benchmarks/llama3_h100_202412_torchtitan.md

This is to unblock https://github.com/pytorch/torchtitan/discussions/1289 and requests from @danielvegamyhre to submit their benchmarking results.
The `benchmarks` folder should be the central place to host torchtitan performance results.

add benchmarks folder and submission guidelines

---

tests/unit_tests/test_checkpoint.py

The original `test_checkpoint.py` had some issues - it mocked the ConfigManager, which made it prone to breaking.
This PR refactors `test_checkpoint.py` to make it more robust and cover additional logic. While there is still room for improvement, this update addresses some of the existing gaps in test coverage.

[BE] Rewrite test_checkpiont.py

---

torchtitan/components/ft.py
torchtitan/config_manager.py
torchtitan/train.py

Summary:
- update to use the changed api to create diloco (we need to pass in model parts)
- add configuration options for streaming diloco
Test Plan:
```
$ NGPU=2 ./run_train.sh --fault_tolerance.enable --fault_tolerance.group_size=1 --fault_tolerance.semi_sync_method=diloco --fault_tolerance.sync_steps=2 --fault_tolerance.replica_id=0 --fault_tolerance.fragment_sync_delay=1 --fault_tolerance.fragment_update_alpha=0.0
[rank0]:[titan] 2025-06-16 09:39:08,893 - root - INFO - Model llama3 debugmodel size: 6,270,208 total parameters
[rank0]:[titan] 2025-06-16 09:39:08,894 - root - INFO - Applied selective activation checkpointing to the model
[rank0]:[titan] 2025-06-16 09:39:08,952 - root - INFO - Applied FSDP to the model
[rank0]:[titan] 2025-06-16 09:39:09,375 - root - WARNING - Peak flops …
```

support torchft streaming diloco

---

torchtitan/config_manager.py

Summary:
document why default parameters are set the way they are for streaming diloco
Test Plan:
```
$ NGPU=2 ./run_train.sh --fault_tolerance.enable --fault_tolerance.group_size=1 --fault_tolerance.semi_sync_method=diloco --fault_tolerance.sync_steps=2 --fault_tolerance.replica_id=0 --fault_tolerance.fragment_sync_delay=1 --fault_tolerance.fragment_update_alpha=0.0
[rank0]:[titan] 2025-06-16 09:39:08,893 - root - INFO - Model llama3 debugmodel size: 6,270,208 total parameters
[rank0]:[titan] 2025-06-16 09:39:08,894 - root - INFO - Applied selective activation checkpointing to the model
[rank0]:[titan] 2025-06-16 09:39:08,952 - root - INFO - Applied FSDP to the model
[rank0]:[titan] 2025-06-16 09:39:09,375 - root - WARNING - Peak flops undefined for: NVIDIA PG509-210, fallback to A100 …
```

document default parameters for streaming diloco

---

tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/config_manager.py

While fail_fast checkpointing feature is useful, it can also waste time and storage when the cluster is already verified with TorchTitan. This PR makes fail_fast feature as optional and defaults to False.

Make checkpoint fail_fast feature optional

---

torchtitan/models/deepseek-v3/model/args.py
torchtitan/models/deepseek-v3/model/model.py
torchtitan/models/deepseek-v3/model/moe.py

1. Attention module
2. MoE module (note: I only implemented the naive routing, not the "node limit routing" strategy)
3. Deepseek-V3 model
Reference:
1. Deepseek-ai: https://github.com/deepseek-ai/DeepSeek-V3/blob/main/inference/model.py
4. Huggingface: https://huggingface.co/deepseek-ai/DeepSeek-V3-Base/blob/main/modeling_deepseek.py
5. torchtitan/experiment/deepseek-v3
6. torchtitan/experiment/llama4

Implement Deepseek-V3 model skeleton

---

torchtitan/experiments/simple_fsdp/simple_fsdp.py

Some regression since https://github.com/pytorch/torchtitan/pull/1273
The issue is python closure could not capture the param name correctly unless you pass it as a input to the lambda function.

Fix the paramterization of simple fsdp

---

torchtitan/models/llama3/infra/parallelize.py

Mitigates #1306 
Following discussions in #1306, the `seq_len%tensor_parallel_degree==0` seems to be a necessary condition for the tp Llama3 model to work (since it is a workaround of [this](https://github.com/pytorch/pytorch/issues/130646) numerical issue in pytorch Dtensors of complex numbers.
This PR makes this requirements explicit.

Add check for `seq_len%tensor_parallel_degree==0` for parallelized Llama

---

.github/workflows/integration_test_8gpu_h100.yaml

As titled, to save some H100 resource and avoid long waiting, only run integration test when PR's base branch is main.
No need to run H100 tests on PRs like #1330

[CI] Only run integration test when PR's base branch is main 

---

torchtitan/models/deepseek_v3/__init__.py
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/deepseek_v3/model/args.py
torchtitan/models/deepseek_v3/model/model.py
torchtitan/models/deepseek_v3/model/moe.py
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml

1. Introduced a basic DSV3-16B model training config
2. Enabled FSDP/HSDP on DSV3-16B model training
Current profiler looks like this: The `to_copy` takes to long and needs to be optimized. The copy comes from dtype conversion in class MoE():         
```routed_output = (routed_output.to(torch.float32) * top_scores.unsqueeze(-1)).to(x.dtype)```
With FSDP only:

[DSV3] Adding 16B model training config, Enable FSDP and AC on DSV3-16B model

---

tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/config_manager.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/llama4/scripts/convert_hf_to_dcp_with_gpus.py
torchtitan/experiments/llama4/scripts/convert_meta_to_dcp_with_gpus.py
torchtitan/train.py

This is a BC breaking change but should be the right way to save the last step checkpoint.

[RFC] Make last_save_model_weights_only default to True

---

scripts/convert_llama_to_dcp.py
scripts/generate/test_generate.py
tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/experiments/llama4/scripts/convert_hf_to_dcp_with_gpus.py
torchtitan/experiments/llama4/scripts/convert_meta_to_dcp_with_gpus.py

We should always ignore freq_cis and other parameters in excluded_parameters_for_model_only to avoid confusion.
TODO: Is this going to break PP with seed checkpoint?

Always ignore freqs_cis

---

torchtitan/experiments/llama4/model/moe.py

Fixes #1353 
Bug is related to this revert, the arg list changed: https://github.com/pytorch/torchtitan/pull/1340
So need to add this arg back: https://github.com/pytorch/torchtitan/commit/4e31b862d1d161b330b64be5b8db52c46c33ba58
cc @lessw2020 @tianyu-l

[llama4] add back max_len arg to generate_permute_indices

---

torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py

Adds a unit test for loading flux dataset from a checkpoint. Creates the new dataloader from a checkpoint then ensures that the next generated labels and tokens are the same in both dataloaders, starting from the checkpoint.

unit test for flux_dataset dataloader checkpointing

---

torchtitan/components/quantization/float8.py

Validate only FSDP, HSDP are used for float8 MoE training. TP support is in progress and CP/PP are untested. 2D+ parallelism are untested as well.
- Command: `NGPU=4 CONFIG_FILE="./torchtitan/experiments/llama4/train_configs/debug_model.toml" ./run_train.sh --training.steps=10 --model.converters="float8" --float8.recipe_name="rowwise"  --float8.moe_fqns_prototype="experts"  --parallelism.tensor_parallel_degree=2`
- Error: `AssertionError: Float8 MoE training prototype does not yet support tensor parallelism`

[float8 moe training] validate float8 moe parallelism config

---

docs/debugging.md

As titled. To avoid someone with the same issue as me to understand why we need "seed checkpoint"

Add debugging instructions for "Reproducibility between runs"

---

docs/checkpoint.md
docs/debugging.md
scripts/estimate/estimation.py
scripts/generate/test_generate.py
tests/unit_tests/test_model_converter.py
torchtitan/components/ft.py
torchtitan/components/optimizer.py
torchtitan/config_manager.py
torchtitan/distributed/parallel_dims.py
torchtitan/distributed/utils.py
torchtitan/experiments/llama4/README.md
torchtitan/experiments/llama4/__init__.py
torchtitan/experiments/llama4/infra/expert_parallel.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/experiments/llama4/model/moe.py
torchtitan/experiments/llama4/optimizer.py
torchtitan/experiments/llama4/train_configs/debug_model.toml
torchtitan/models/llama3/infra/parallelize.py
torchtitan/protocols/train_spec.py
torchtitan/train.py

**Overview**
Previously I demonstrated Expert Parallel for expert-choice MoE in a stack of PRs https://github.com/pytorch/torchtitan/pull/732.
This PR adds the initial support of dp2ep Expert Parallel for token-choice MoE, being non-intrusive to model code and composable with other parallelisms. In particular:
- FSDP/HSDP + TP + EP is unblocked by https://github.com/pytorch/pytorch/pull/157216
- fused optimizer for dp2ep EP is unblocked by https://github.com/pytorch/pytorch/pull/157682
This PR also fixes the issue between auxiliary-loss-free load balancing and gradient accumulation, partly inspired by the solution of @hann-wang in https://github.com/pytorch/torchtitan/pull/1304 which originally pointed out the issue. This PR does the expert bias update in an optimizer hook, instead of …

dp2ep Expert Parallel

---

scripts/generate/test_generate.py

Since https://github.com/pytorch/torchtitan/pull/1338 the `freqs_cis` buffer is no longer persisted/read in any code path with the intention being that it is re-calculated at the model loading/initialization. However this requires calling `init_weights` on the model, which `scripts/test_generate.py` currently is not doing.
As of right now running generation on the pretrained Llama 3 models will result in garbled outputs
Convert weights: `python ./scripts/convert_llama_to_dcp.py /home/emozilla/hf/Llama-3-8B/original /home/emozilla/dcp/Llama-3-8B`
Run generation: `CONFIG_FILE=./torchtitan/models/llama3/train_configs/llama3_8b.toml CHECKPOINT_DIR=/home/emozilla/dcp/Llama-3-8B PROMPT="A long time ago in a galaxy far, far away" ./scripts/generate/run_llama_generate.sh`
HEAD
``` …
```

call init_weights before generation

---

tests/integration_tests.py
torchtitan/components/validate.py
torchtitan/config_manager.py
torchtitan/datasets/hf_datasets.py
torchtitan/models/llama3/__init__.py
torchtitan/models/llama3/train_configs/debug_model.toml
torchtitan/protocols/train_spec.py
torchtitan/train.py

Update PR Summary:
Implements a validator that can be easily plugged into the training loop and configured from the job specific config file.
Changes:
- Created validation section in job_config with enabled, dataset, freq, and steps fields
- Created a builder function for validator in train_spec
- Created a separate builder function for validation dataset in hf_dataset.py
- Created validator class
- Validator class initializes a build_validation_hf_loader but leaves this dataloader function unexposed to the train_spec
- Validator class supports ddp, fsdp, cp, and tp (but not pp yet)
- Integrated validation call into training loop
- Creates an integration test to test parallelization
Updated tests training the same base model weights from a seed checkpoint:
| FSDP=2 | FSDP=2,TP=4 |
| --- | …

basic validator implementation

---

README.md
scripts/download_tokenizer.py
tests/unit_tests/test_tokenizer.py
torchtitan/config_manager.py

Fix https://github.com/pytorch/torchtitan/pull/1333#discussion_r2198946174
Downloading from both `Meta-Llama-3.1-8B` and `Llama-3.1-8B` work, but the README instructions and the .toml file are different. This changes so the README matches

Fix tokenizer README repository ID

---

torchtitan/tools/utils.py

This pr fix what seems to be a wrong estimation of the peak flops for the B200. With the current code the peak flops of B200 is 4.5x bigger that H100 which seems off. It seems that the number reported https://nvdam.widen.net/s/wwnsxrhm2w/blackwell-datasheet-3384703 are with 2:4 sparsity ?

fix wrong b200 flops number

---

scripts/estimate/estimation.py
scripts/generate/test_generate.py
tests/unit_tests/test_model_converter.py
tests/unit_tests/test_train_spec.py
torchtitan/components/checkpoint.py
torchtitan/components/optimizer.py
torchtitan/components/tokenizer.py
torchtitan/components/validate.py
torchtitan/distributed/parallel_dims.py
torchtitan/distributed/utils.py
torchtitan/experiments/deepseek_v3/__init__.py
torchtitan/experiments/deepseek_v3/train_ds_real.py
torchtitan/experiments/flux/__init__.py
torchtitan/experiments/flux/infra/parallelize.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/llama4/__init__.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/experiments/llama4/optimizer.py
torchtitan/experiments/multimodal/__init__.py
torchtitan/experiments/simple_fsdp/__init__.py
torchtitan/experiments/simple_fsdp/parallelize.py
torchtitan/experiments/simple_fsdp/tests/test_numerics.py
torchtitan/models/deepseek_v3/__init__.py
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/llama3/__init__.py
torchtitan/models/llama3/infra/parallelize.py
torchtitan/models/llama3/infra/pipeline.py
torchtitan/protocols/train_spec.py
torchtitan/tools/utils.py
torchtitan/train.py

This PR does the following:
1. move `world_mesh` into `ParallelDims`, as they have a close relationship
2. move `enable_loss_parallel` out of `ParallelDims` constructor
3. add a convenient property `seq_len_divisor` to `ParallelDims`
4. set `dataloader` and `ft_manager` as optional in `CheckpointManager`
5. some minor improvements on typing and code organization

refactor ParallelDims and CheckpointManager

---

torchtitan/components/metrics.py
torchtitan/components/validate.py
torchtitan/tools/utils.py
torchtitan/train.py

Integrated the validator together with metrics processor for better metrics logging.
Key changes:
- Metrics processor is passed to validator within training loop
- Validator can reuse metrics processor's built-in functionalities such as memory profiling, throughput tracking, and tensorboard/wandb logging
This is how the new logging looks from terminal:

Validator integration with current metrics processor for logging

---

scripts/estimate/estimation.py
torchtitan/components/ft.py
torchtitan/components/optimizer.py
torchtitan/distributed/utils.py
torchtitan/experiments/llama4/optimizer.py
torchtitan/protocols/train_spec.py
torchtitan/train.py

This PR refactors `FTManager` to:
1. simplify construction logic
2. expose simpler interfact to `train.py`
3. make it optional when building optimizer
and some other minor improvements.

refactor FTManager

---

torchtitan/experiments/llama4/model/moe.py
torchtitan/experiments/llama4/train_configs/debug_model.toml
torchtitan/models/deepseek_v3/model/moe.py

As titled. 
Tested on llama4 debugging model (dp=8, ep=2):

[llama4] Change expert_bias and tokens_per_expert to non-persistent buffer

---

torchtitan/components/metrics.py
torchtitan/tools/profiling.py

Summary:
- log the tensorboard for ft replicas to a separate folder
- log profiles for ft replicas to a separate folder
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchtitan/pull/1410).
* #1411
* __->__ #1410

separate outputs for ft replicas

---

torchtitan/components/ft.py
torchtitan/components/metrics.py
torchtitan/config_manager.py
torchtitan/tools/profiling.py

Summary:
- allow using gloo process group
- add a parameter to the ft config
- only nccl and gloo will be supported for now
---
[//]: # (BEGIN SAPLING FOOTER)
Stack created with [Sapling](https://sapling-scm.com). Best reviewed with [ReviewStack](https://reviewstack.dev/pytorch/torchtitan/pull/1411).
* __->__ #1411
* #1410

allow specifying ft pg

---

tests/integration_tests.py
torchtitan/experiments/llama4/model/args.py
torchtitan/models/llama3/model/args.py

Stacked PRs:
* __->__#1408
--- --- ---
Remove flex+compile restriction
Recently enabled this w/  https://github.com/pytorch/pytorch/pull/150080
Before the change I got:
```Shell
[rank0]:[rank0]:   File "/home/drisspg/meta/torchtitan/torchtitan/models/llama3/model/args.py", line 48, in update_from_config
[rank0]:[rank0]:     raise ValueError(
[rank0]:[rank0]: ValueError: FlexAttention is not compatible with selective AC yet. See https://github.com/pytorch/pytorch/issues/147879
```
I tried running this locally with;
```
CONFIG_FILE="./torchtitan/models/llama3/train_configs/debug_model.toml" NGPU=1 ./run_train.sh --model.flavor
debugmodel_flex_attn --training.compile
```
Got:
If there are other more robust testing we can do I am down I am trying to unblock some internal users and ensure I …

Remove flex+sac restriction

---

tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/components/ft.py
torchtitan/train.py

This PR takes job_config out of the CheckpointManager class. Why? JobConfig is a monolith -- it has knowledge of every part of a titan training job. As a result, it is hard to actually use CheckpointManager in a standalone fashion. In practice the job config is mostly only used for its checkpoint config, plus two other usages as far as I can tell:
1) Getting the replica_id from the FTManager
2) Taking the dump_folder from the job field and joining it with the checkpoint folder
For (1) we can just get this directly from FTManager without accessing the JobConfig field. For (2) we can pass `job_config.job.dump_folder` explicitly as a base folder, then join to `checkpoint_config.folder`. Personally I would try to consolidate `job.dump_folder` and `checkpoint.folder` (though I understand there …

Take job config out of checkpoint manager

---

torchtitan/experiments/forge/README.md
torchtitan/experiments/forge/__init__.py
torchtitan/experiments/forge/engine.py
torchtitan/experiments/forge/example_train.py
torchtitan/experiments/forge/job_config.py
torchtitan/experiments/forge/train_spec.py

depending on https://github.com/pytorch/torchtitan/pull/1384 and https://github.com/pytorch/torchtitan/pull/1397

add the forge folder

---

README.md
scripts/estimate/estimation.py
scripts/generate/test_generate.py
tests/integration_tests.py
tests/unit_tests/test_lr_scheduler.py
tests/unit_tests/test_train_spec.py
torchtitan/components/checkpoint.py
torchtitan/components/lr_scheduler.py
torchtitan/components/optimizer.py
torchtitan/config/__init__.py
torchtitan/config/job_config.py
torchtitan/distributed/utils.py
torchtitan/experiments/forge/engine.py
torchtitan/experiments/forge/example_train.py
torchtitan/experiments/llama4/optimizer.py
torchtitan/protocols/train_spec.py
torchtitan/tools/profiling.py
torchtitan/train.py

In general it is anti-pattern to globally depend on a monolithic `JobConfig` everywhere. This PR takes the first step to remove this pattern.
After this PR, the issue remains for parallelize & pipeline functions, metrics processor, tokenizer, dataloader, validator, etc.
A note is that when refactoring tokenizer, dataloader, validator, we should still allow users to extend easily beyond. This may require the signature of builder functions to take additional args / kwargs.
I'm also disabling some PP tests, which starts to fail on the latest torch nightly
https://github.com/pytorch/torchtitan/actions/runs/16484633329/job/46606801605

[refactor] moving gloabl dependence on JobConfig to fine-grained configs

---

torchtitan/components/quantization/mx.py
torchtitan/config/job_config.py

Stacked PRs:
* __->__#1427
--- --- ---
make mxfp8 dim1 cast kernel configurable
- We recently added a new CUDA kernel for the mxfp8 dim1 cast which is ~1.4x faster than the existing Triton kernel or torch.compile, and using it results in an e2e training speedup of  +1.5-2.5% TPS with Llama3 8b using FSDP=4/8 (https://github.com/pytorch/ao/pull/2513). The integration work for composability with torch.compile + FSDP is complete as well: https://github.com/pytorch/ao/pull/2564
- This PR updates the mxfp8 user facing API to replace the boolean flag `"--mx.use_triton_for_dim1_cast=[true|false]` to `mxfp8_dim1_cast_kernel_choice=[triton|cuda|torch]`
- Triton: `NGPU=8 CONFIG_FILE="./torchtitan/models/llama3/train_configs/llama3_8b.toml" ./run_train.sh --training.steps=100 --model.converters="mx" …

make mxfp8 dim1 cast kernel configurable

---

torchtitan/components/checkpoint.py

This PR fixes a potential `NoneType` attribute error in the checkpoint purging code. Previously, when the regex did not find a match (i.e., there exists a file of other format), the code would attempt to access `match.group(1)` and raise an none pointer exception:
```
[rank0]: Traceback (most recent call last):
[rank0]:   File "~/.conda/envs/forge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
[rank0]:     return _run_code(code, main_globals, None,
[rank0]:   File "~/.conda/envs/forge/lib/python3.10/runpy.py", line 86, in _run_code
[rank0]:     exec(code, run_globals)
[rank0]:   File "~/forge/apps/sft/main.py", line 271, in <module>
[rank0]:     sys.exit(recipe_main())
[rank0]:   File "~/forge/forge/config/parse.py", line 174, in wrapper
[rank0]: …
```

Fix a none pointer exception in checkpoint.py

---

docs/checkpoint.md
tests/integration_tests.py
torchtitan/components/checkpoint.py
torchtitan/config/job_config.py

This PR
- removes `_load_checkpoint_in_hf_format` and always let user enable `initial_load_in_hf`, which makes it symmetric to `last_save_in_hf` and less ambiguous
- require `intial_load_path` to be used, instead of letting user figure out they can download HF checkpoint to `checkpoint.folder / step-0 / ` which is not intuitive.

[checkpoint] let user specify `intial_load_path` and `initial_load_in_hf` when using HF checkpoints

---

torchtitan/models/llama3/infra/parallelize.py
torchtitan/tools/utils.py
torchtitan/train.py

according to discussions in https://github.com/pytorch/torchtitan/issues/1091
The CI failure is because `FSDPMemTracker` is not compatible of `fully_shard` on a list of modules. @sanketpurandare will help address this soon. Let's land it after the feature is available.

improve reshard_after_forward logic

---

torchtitan/components/tokenizer.py
torchtitan/config/job_config.py

We don't use `tokenizer.model` anymore

Fix tokenizer error message

---

.github/workflows/integration_test_8gpu.yaml
.github/workflows/integration_test_8gpu_flux.yaml
.github/workflows/integration_test_8gpu_h100.yaml
.github/workflows/integration_test_8gpu_simple_fsdp.yaml
.github/workflows/integration_test_8gpu_torchft.yaml

Somehow, despite the logs showing echo-ing the driver version successfully, it exits with code 1. 
This PR attempts guard against the case where the command writes to stdout successfully but exits with code 1 for some reason.
https://github.com/pytorch/torchtitan/blob/881f0ca465d26ab87ccfc5c89572b8a21c4e9707/.github/workflows/integration_test_8gpu.yaml#L44

guard against nvidia-smi command exit code 1

---

torchtitan/models/deepseek_v3/README.md
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml

Based on the discussion in this PR (https://github.com/pytorch/torchtitan/pull/1495), the conclusion was to ensure that 16B uses the proper tokenizer to avoid the cudaAssertError in the current config which comes from mismatch between embeddings and tokenizer vocab.
Thus, this PR;
1 - adds additional line to the readme for enabling users to pull the 16B-chat tokenizer, 
2- updates the 16_toml config to point to the 16B tokenizer under /assets/tokenizer/deepseek-moe-16b-chat
With that, the vocab size of 102400 already in the toml now works flawlessly. 
**Testing:**
run download tokenizer 
run 20 iters with 16B without issue.

[deepseek] integrate 16B tokenizer to match 16B official model

---

tests/integration_tests.py
torchtitan/components/validate.py
torchtitan/train.py

With recent api change to pipeline schedule https://github.com/pytorch/pytorch/pull/157795, we can now schedule forward pass and calculate loss, allowing us to use validation and pp together.
To test correctness we train from a seed checkpoint with training.seed and training.determinism set with varying degrees of parallelism and different pipeline schedules to compare if loss remains the same:
| Parallelism | Loss |
| --- | --- |
| FSDP=2 | <img width="960" height="328" alt="Screenshot 2025-07-29 at 5 12 49 PM" src="https://github.com/user-attachments/assets/3aedc87d-f12c-409c-88da-86b0ac72a1a7" /> |
| FSDP=2, TP=2, PP=2, PP_schedule="1F1B" |  <img width="964" height="334" alt="Screenshot 2025-07-29 at 5 17 18 PM" src="https://github.com/user-attachments/assets/b5f8979b-0f44-48fc-aa4d-38e …

validation support for pipeline parallelism [WIP]

---

torchtitan/models/deepseek_v3/__init__.py
torchtitan/models/deepseek_v3/model/model.py

* __->__ #1504
**Summary**
Before the change:
```
File "/data/users/xilunwu/pytorch/torch/nn/modules/module.py", line 1784, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/users/xilunwu/pytorch/torch/nn/modules/normalization.py", line 414, in forward
return F.rms_norm(x, self.normalized_shape, self.weight, self.eps)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/users/xilunwu/pytorch/torch/nn/functional.py", line 2924, in rms_norm
return torch.rms_norm(input, normalized_shape, weight, eps)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: device-side assert triggered
Search for `cudaErrorAssert' in …
```

[DSV3] Add output.contiguous() in model to match llama3

---

torchtitan/components/quantization/float8.py
torchtitan/components/quantization/mx.py
torchtitan/config/job_config.py
torchtitan/experiments/llama4/infra/expert_parallel.py

- For mxfp8, token group sizes must be multiples of "block_size" because in the backward pass for `grad_weight = grad_output_t @ input`, the "M" (token) dimension is the contracting dimension, and each token group is a logically distinct subtensor, so we scale them separately. This means token groups contracting dimension must be divisible by the mxfp8 block_size (default 32). Here is a diagram showing the problem: https://www.internalfb.com/excalidraw/EX521879
- To solve this, this PR makes the token group M aligment configurable.
- Integration test with torchao passes: https://github.com/pytorch/ao/pull/2642
- Did manual test run with llama4 debug model using bf16

Make token group alignment size configurable

---

torchtitan/models/deepseek_v3/model/model.py

* __->__ #1504
**Summary**
Before the change:
```
File "/data/users/xilunwu/pytorch/torch/nn/modules/module.py", line 1784, in _call_impl
return forward_call(*args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/users/xilunwu/pytorch/torch/nn/modules/normalization.py", line 414, in forward
return F.rms_norm(x, self.normalized_shape, self.weight, self.eps)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/data/users/xilunwu/pytorch/torch/nn/functional.py", line 2924, in rms_norm
return torch.rms_norm(input, normalized_shape, weight, eps)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.AcceleratorError: CUDA error: device-side assert triggered
Search for `cudaErrorAssert' in …
```

[DSV3] Add output.contiguous() in model to match llama3 (#1504)

---

torchtitan/components/quantization/mx.py
torchtitan/config/job_config.py

Summary:
Instead of maintaining a mapping in torchtitan with valid mx recipe names, just pass the string recipe directly to torchao.  This way torchao can iterate on recipes without any changes to torchtitan to use those recipes. Note that appropriate error messages will be thrown from torchao if user specifies an invalid config name, so there is no need to duplicate them in torchtitan.
Test Plan:
```bash
with-proxy CONFIG_FILE="torchtitan/models/llama3/train_configs/debug_model.toml" ./run_train.sh --model.print_after_conversion --training.compile --training.steps 50 --model.converters mx --mx.recipe_name "mxfp8_cublas_rceil"
```
Reviewers:
Subscribers:
Tasks:
Tags:

make mx recipe name more generic

---

torchtitan/distributed/utils.py
torchtitan/train.py

Currently, `ntokens_seen` is only locally logged. I think it is almost always desirable to only track the global quantity (the only use case I can see for per-device tracking is for debugging?).
Therefore, I propose to all-reduce `ntokens_seen` before logging.

All-reduce `ntokens_seen` before logging

---

torchtitan/components/validate.py

Currently, the first time validation metrics are computed is when `step == job_config.validation.freq`. I think it is preferable to always compute them for the first step as well.

Compute validation metrics at first step

---

torchtitan/experiments/llama4/infra/expert_parallel.py
torchtitan/experiments/llama4/model/moe.py

Rather than store experts weights pre-transposed (E, in_dim, out_dim), we should store the expert weights non-transposed (E, out_dim, in_dim) then transpose before grouped gemm for (1) compatible dims for gemm, and (2) column-major memory layout required for right operand in grouped gemm. Doing this simple transpose (metadata change only) is must more efficient than doing this [inefficient memory layout transformation before every GEMM in fp8](https://github.com/pytorch/ao/blob/6e941c87c4d9fb9a74e6f979dd522605c696ca42/torchao/prototype/moe_training/scaled_grouped_mm.py#L96). 
Llama4 debug model with FSDP=8, using config:
```python
"debugmodel": TransformerModelArgs(
dim=5120,
n_layers=4,
n_heads=40,
n_kv_heads=8,
ffn_dim_multiplier=1.2,
multiple_of=2048,
rope_theta=500000, …
```

[llama4] store expert weights such that we can transpose before grouped mm to have col-major memory layout

---

torchtitan/experiments/llama4/infra/parallelize.py

We should add an `apply_compile` function for llama4 that uses fullgraph=False for MoE layers and fullgraph=True for dense layers. 
I keep manually applying this hack during development to test compile composability, but IMO we should have this merged and update to use fullgraph=True everywhere once that is supported. 
cc @xmfan @tianyu-l any thoughts?

[llama4] add apply_compile for moe, where fullgraph=False for moe layers

---

torchtitan/models/deepseek_v3/README.md
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml

This PR updates to use base rather than chat (they are the same but name is different) and makes it clear we are not loading the model weights for 16b. 
Testing:
download via script
run 20 iters with 16b_base tokenizer.

[deepseek] update to 16b base tokenizer

---

torchtitan/components/validate.py
torchtitan/experiments/flux/__init__.py
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/job_config.py
torchtitan/experiments/flux/model/validate.py
torchtitan/experiments/flux/sampling.py
torchtitan/experiments/flux/tests/integration_tests.py
torchtitan/experiments/flux/tests/test_generate_image.py
torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py
torchtitan/experiments/flux/train.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml
torchtitan/experiments/flux/validate.py
torchtitan/experiments/multimodal/tokenizer/tiktoken.py

The paper shows that creating 8 equidistant timesteps and calculating the average loss on them will result in a highly correlated loss to external validation methods such as CLIP or FID score.
This pr's implementation rather than creating 8 stratified timesteps per sample, only applies one of these equidistant timesteps to each sample in a round-robin fashion. Aggregated over many samples in a validation set, this should give a similar validation score as the full timestep method, but will process more validation samples quickly.
- Integrates the image generation evaluation in the validation step, users can 
- Refactors and combines eval job_config with validation
- Adds an `all_timesteps` option to the job_config to choose whether to use round robin timesteps or full timesteps per sample …

Flux Validation

---

torchtitan/components/ft/diloco/utils.py
torchtitan/components/ft/manager.py

Summary:
- wasn't seeing print statements getting printed
- the statements show up using the logger
- also added some logging to validate the model is being split for diloco

use logger in ft

---

torchtitan/distributed/utils.py

The current EP grad clipping logic assumes that when using EP all of the norms returned by `torch.nn.utils.get_total_norm` are `DTensor`s. This assumption can be violated and the subsequent `full_tensor` call can correspondingly fail in the edge case where  the [ep_grad list](https://github.com/pytorch/torchtitan/blob/a1fdd7e43694bbfeff5d6ad8ac738c067bb90d41/torchtitan/distributed/utils.py?plain=1#L408) is empty, in which case `get_total_norm` returns `tensor(0.)`, a non-`DTensor`.   
https://github.com/pytorch/torchtitan/blob/a1fdd7e43694bbfeff5d6ad8ac738c067bb90d41/torchtitan/distributed/utils.py?plain=1#L421-L423
```
File "/app/torchtitan/torchtitan/distributed/utils.py", line 423, in _clip_grad_norm_with_ep
).full_tensor()
^^^^^^^^^^^
AttributeError: 'Tensor' object has no attribute …
```

fix: ep clipping with no ep grads

---

torchtitan/train.py

If validation and checkpoint occur on the same training step, do checkpointing first

Reorder validate and checkpoint in train

---

torchtitan/experiments/auto_parallel/parallelize_llama.py

IMO we should just add the loss in the model and let autoparallel parallelize it for us. But for now, let's follow how the other models are implemented

Add support for loss parallel

---

torchtitan/distributed/parallel_dims.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/models/deepseek_v3/infra/parallelize.py

issue pointed out in
https://github.com/pytorch/torchtitan/pull/1534#issuecomment-3157429435
https://github.com/pytorch/pytorch/issues/160285
solution given by @rakkit in https://github.com/pytorch/torchtitan/pull/1534#issuecomment-3157429435

fix EP fsdp gradient divide factor

---

torchtitan/experiments/flux/dataset/tokenizer.py
torchtitan/experiments/flux/inference/infer.py
torchtitan/experiments/flux/inference/prompts.txt
torchtitan/experiments/flux/inference/run_infer.sh
torchtitan/experiments/flux/job_config.py
torchtitan/experiments/flux/run_train.sh
torchtitan/experiments/flux/sampling.py
torchtitan/experiments/flux/train_configs/debug_model.toml

This PR reuses the trainer's parallelization to perform batched inference on Flux. It follows up from and addresses comments on @CarlosGomes98 https://github.com/pytorch/torchtitan/pull/1227. This irons out some optimizations for better code clarity.
In this implementation saves images locally from each rank but maintains the global information such as prompt and idx of each image.  It also removes unnecessary padding and handles prompt sets that are not divisible by the batch size.

Flux Batched Inference

---

torchtitan/experiments/kernels/moe/combine.py

Added class `TokenCombiner` which combines tokens from different experts, with backward support.
Usage:
```
combiner = TokenCombiner(group_name, align, max_inp_len, max_out_len, inp.shape[1:], world_size, ne, dtype)
output = combiner(inp, out, in_splits_offsets, out_splits_offsets)
```
Supports:
```
torch.compile(combiner)
```

[a2av] Add autograd support for token combine op

---

scripts/checkpoint_conversion/convert_to_hf.py
torchtitan/components/checkpoint.py
torchtitan/experiments/forge/train_spec.py
torchtitan/models/README.md
torchtitan/models/llama3/model/state_dict_adapter.py
torchtitan/protocols/__init__.py
torchtitan/protocols/state_dict_adapter.py
torchtitan/protocols/train_spec.py

This moves the logic that parses `model.safetensors.index.json` and generates the `fqn_to_index_mapping` to `StateDictAdapter` since this logic should be shared by all classes that inherit from `StateDictAdapter`.

Move fqn mapping logic to StateDictAdapter

---

torchtitan/experiments/forge/engine.py

This was broken by #1526, updating to match the changes in train.py. Tested via a run in forge

fix state dict adapter in forge engine

---

tests/unit_tests/test_download_hf_assets.py

This pr adds unit tests for the download_hf_assets script. It mocks the `huggingface_hub.list_repo_files` and `huggingface_hub.hf_hub_download` functions to represent the `meta-llama/Llama-3.1-8B` repository.
Tests:
- script downloads the correct files when called with each `asset_types`
- script downloads correct files when called with `download_all`
- script matches and downloads files correctly according to `additional_patterns`
- script checks that matching works properly for nested files
- tests missing file warning for when no matches are found
- tests download failure warning when HTTP 404 error happens
- tests correct error raised for incorrect repo_id format
- tests correct error raised for unknown `asset_types`

unit test for download_hf_assets script

---

scripts/estimate/estimation.py
scripts/generate/test_generate.py
tests/unit_tests/test_model_converter.py
torchtitan/config/job_config.py
torchtitan/distributed/expert_parallel.py
torchtitan/distributed/parallel_dims.py
torchtitan/experiments/forge/engine.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/experiments/llama4/train_configs/debug_model.toml
torchtitan/experiments/llama4/train_configs/llama4_17bx128e.toml
torchtitan/experiments/llama4/train_configs/llama4_17bx16e.toml
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/deepseek_v3/train_configs/debug_model.toml
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_671b.toml
torchtitan/models/moe.py
torchtitan/train.py

This is a followup of original EP support https://github.com/pytorch/torchtitan/pull/1324
[TBA] description + figure
setup
- optimizer Adam
- steps 100, warmup_steps 20
- seed 42
comparison set
- FSDP 2
- FSDP 2, CP 2, TP 2, EP 8, ETP 1
- FSDP 2 (EP 2), PP 2, TP 2 (ETP 2)

[EP] add support for ETP=1

---

torchtitan/distributed/expert_parallel.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/experiments/llama4/model/args.py
torchtitan/experiments/llama4/scripts/convert_hf_to_dcp_with_gpus.py
torchtitan/models/deepseek_v3/model/args.py
torchtitan/models/deepseek_v3/model/model.py
torchtitan/models/deepseek_v3/model/state_dict_adapter.py
torchtitan/models/moe.py

**apply dim-1 FSDP sharding for routed experts when `dp_mod_ep * ep > num_experts`**
This is because our routed experts are defined of shape `(num_experts, ..., ...)`. EP already shards on dim-0. FSDP's default dim-0 sharding + EP sharding will be inefficient when `dp_mod_ep * ep > num_experts`.
Tested:
with 8 experts FSDP2 EP4, we see default dim-0 sharding
> [rank0]:w1 DTensor(local_tensor=tensor(..., device='meta', size=(1, 512, 256)), device_mesh=DeviceMesh((dp_shard_mod_ep=2, ep=4), device: 'cuda', stride: (4, 1)), placements=(_StridedShard(dim=0, sf=4), Shard(dim=0)))
[rank0]:w2 DTensor(local_tensor=tensor(..., device='meta', size=(1, 256, 512)), device_mesh=DeviceMesh((dp_shard_mod_ep=2, ep=4), device: 'cuda', stride: (4, 1)), placements=(_StridedShard(dim=0, sf=4), Shard(dim=0))) …

[MoE/EP] apply dim-1 FSDP sharding for routed experts and rewrite shared experts with FFN

---

torchtitan/distributed/pipeline_parallel.py

DualPipeV was added to pt-core (https://github.com/pytorch/pytorch/pull/159591) so just adding code to support it in titan
To use, in .toml file set:
```
pipeline_parallel_schedule = "DualPipeV"
```
Ideally we don't have this if-statement check, so as a future BE task I can look into removing it

Add DualPipeV

---

torchtitan/config/manager.py

This allows us to use `--model.tokenizer_path=` to invalidate `tokenizer_path`.

Ignore tokenizer_path if it is an empty string

---

torchtitan/components/tokenizer.py

Adds a check to see if the old tokenizer path is being used when tokenizer path fails. This way it can provide guidance to people to update to the supported `hf_assets_path` and `download_hf_assets.py` script

added better guidance for if deprecated tokenizer path fails

---

torchtitan/experiments/llama4/infra/parallelize.py

As titled.
It seems with this PR, prefetching works as expected, both in forward and in backward.
This is developed on top of the example https://github.com/pytorch/torchtitan/pull/1581 from @weifengpy 
I verified in profiler trace, but it's a bit hard to show in a picture.

MoE explicit prefetching in FSDP

---

scripts/generate/test_generate.py
tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/experiments/llama4/model/model.py
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/deepseek_v3/model/model.py
torchtitan/models/llama3/model/model.py

As PP didn't need persistent buffer, and `torch.compile` works with non-persistent buffer now, change freq_cis from persistent buffer to non-persistent buffer . In this way, checkpointer doesn't need to explicitly exclude freq_cis when loading.
1. llama3 model with torch.compile ✅
2. llama4 model with torch.compile ✅
3. deepseek-v3 model with torch.compile ✅

Change freq_cis from persistent buffer to non-persistent buffer

---

scripts/checkpoint_conversion/convert_from_hf.py
scripts/checkpoint_conversion/convert_to_hf.py
scripts/download_hf_assets.py
torchtitan/experiments/flux/__init__.py
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/model/state_dict_adapter.py
torchtitan/experiments/flux/validate.py
torchtitan/protocols/state_dict_adapter.py

This PR adds the `FluxStateDictAdapter`, allowing us to convert checkpoints to and from HF.
Additional changes:
- Modifies `download_hf_assets` script to support downloading diffusion-type safetensor files
- Registers Flux's `TrainSpec` in `convert_from_hf` and `convert_to_hf` so that conversion script can be reused
- e.g. `python ./scripts/checkpoint_conversion/convert_from_hf.py ./assets/hf/FLUX.1-dev/transformer ./outputs/temp --model_name flux --model_flavor flux-dev`
Tests:
Performing KL divergence test on the forward pass of converted weights loaded in `torchtitan` and HF weights loaded with HF `FluxTransformer2DModel`, we get:
```
Average loss for test from_hf is 7.233546986222528e-13
```
Addiitonally, we can now run inference with HF weights to verify changes made in …

[HF] Model Definition Conversion Support for FLUX

---

torchtitan/components/optimizer.py
torchtitan/models/moe.py

We put all experts' usage into a buffer such that we only need one reduce rather than #number-of-layers times
Additionally, handle cases where tokens per expert are counted twice during full recompute.

improve MoE bias update logic in optimizer

---

torchtitan/distributed/tensor_parallel.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/llama3/infra/parallelize.py

This PR addresses duplicated code related to enabling async TP across different parts of the codebase. It introduces a new API, `maybe_enable_async_tp()`, which centralizes the enablement logic and is reused consistently in all models.
Note that while this PR fixes one async TP bug in TorchTitan, it does not fully resolve https://github.com/pytorch/torchtitan/issues/1613, as there appear to be additional bugs in PyTorch's async TP implementation.

Centralize Async TP Enablement with maybe_enable_async_tp API

---

torchtitan/components/dataloader.py
torchtitan/experiments/forge/example_train.py
torchtitan/train.py

The DataloaderStopIteration exception inherited from StopIteration. According to PEP 479, raising a StopIteration subclass from a generator causes a RuntimeError in Python 3.7+.
This change modifies the base class to `Exception` to ensure it can be caught correctly by user code without triggering this behavior.
Fixes ISSUE #1626

fix(dataloader): Prevent RuntimeError from DataloaderStopIteration

---

torchtitan/experiments/qwen3/__init__.py

As titled. Only enable weight tying for smaller model

[Qwen3] Fix weight tying for Qwen3 according to Huggingface configs

---

torchtitan/components/validate.py
torchtitan/config/job_config.py
torchtitan/datasets/hf_datasets.py
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/train_configs/debug_model.toml
torchtitan/experiments/flux/train_configs/flux_dev_model.toml
torchtitan/experiments/flux/train_configs/flux_schnell_model.toml
torchtitan/experiments/flux/validate.py
torchtitan/models/llama3/train_configs/llama3_405b.toml
torchtitan/models/llama3/train_configs/llama3_70b.toml
torchtitan/models/llama3/train_configs/llama3_8b.toml

As the [discussion](https://github.com/pytorch/torchtitan/issues/1618#issuecomment-3215472411), I added:
- warning message when the validation `steps`=-1 in both comment and logger
- change the default `steps` to reasonable values with the common setup (world size = 8).  
- Add infinite loop support for validator to avoid hang when `steps` is large enough to exhaust the dataset.
- Add the same fix for flux.
- 8 GPUs with `steps=-1`: hang around step 1270
- 8 GPUs with `steps=1200`: good
- 8 GPUs with `steps=1500`: `infinite` automatically set to true. Exhaust the dataset and re-iterate, but won't hang
- Flux: `steps=-1` doesn't hang
- Flux: `steps=60` doesn't hang; re-loop the dataset.
Full thread: https://github.com/pytorch/torchtitan/issues/1618
cc @ebsmothers @tianyu-l

Solving the validation hanging issue

---

.github/CODEOWNERS

As titled.  Adding folks as code owner for forge folder.
After the change
1. When there's PR to forge folder, code owners users will get auto tagged.
2. At least one of all the Forge code owners need to approve the PR. 
cc @pbontrager @ebsmothers  @joecummings  @tianyu-l

Add CODEOWNERS for experiments/forge

---

tests/unit_tests/test_activation_checkpoint.py
torchtitan/config/job_config.py
torchtitan/distributed/activation_checkpoint.py
torchtitan/distributed/expert_parallel.py

Depends on https://github.com/pytorch/pytorch/pull/160781
This PR:
- Add config to AC to toggle early-stop with a default of False
- Reverts A2A autograd.Function workaround
More context in https://github.com/pytorch/torchtitan/issues/1467#issuecomment-3181235004
Leak reproable from @tianyu-l 's comment:
```
CONFIG_FILE=./torchtitan/experiments/llama4/train_configs/debug_model.toml ./run_train.sh --parallelism.expert_parallel_degree=2 --activation_checkpoint.mode=full
```
Without early-stop=False:
```
[rank0]:[titan] 2025-08-18 06:07:18,537 - root - INFO - step:  1  loss:  8.0588  grad_norm:  1.4694  memory:  0.82GiB(1.03%)  tps: 4,900  tflops: 0.37  mfu: 0.12%
[rank0]:[titan] 2025-08-18 06:07:18,538 - root - INFO - Synchronizing and adjusting timeout for all ProcessGroups to 0:01:40 …
```

Add config to AC to toggle early-stop and revert A2A autograd.Function workaround

---

torchtitan/distributed/parallel_dims.py

Big fan of torchtitan! Wasnt sure if you guys merged small type hint fixes. No worries if not.
This was just annoying for me in VSCode because I couldnt get it to autocomplete DeviceMesh attributes without the proper type hint

fix small typo in type hint

---

tests/unit_tests/test_activation_checkpoint.py
torchtitan/distributed/activation_checkpoint.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/experiments/qwen3/infra/parallelize.py
torchtitan/experiments/simple_fsdp/parallelize.py
torchtitan/models/deepseek_v3/infra/parallelize.py
torchtitan/models/llama3/infra/parallelize.py

This PR refactors the `apply_ac` implementation by moving `save_list` out of `activation_checkpoint.py` and making it an argument of `apply_ac()`. This change improves configurability without altering the behavior of any models, as the set of operations saved remains unchanged after this PR.

Make SAC save_list configurable

---

torchtitan/experiments/auto_parallel/README.md
torchtitan/train.py

as titled, this pr adds entry to simplefsdp's autobucketing pass in autoparallel. original code is in: https://github.com/pytorch/pytorch/pull/160282
The main code for autobucketing pass will be added to autoparallel repo.

add simplefsdp's autobucketing pass entry

---

torchtitan/distributed/activation_checkpoint.py
torchtitan/distributed/expert_parallel.py
torchtitan/experiments/llama4/infra/parallelize.py
torchtitan/models/deepseek_v3/infra/parallelize.py

```
CONFIG_FILE=./torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml ./run_train.sh --parallelism.expert_parallel_degree 4 --model.hf_assets_path "./assets/hf/deepseek-moe-16b-base"
```
Before (not saving a2a and to_copy)
```
[rank0]:[titan] 2025-09-01 16:03:30,779 - root - INFO - step:  1  loss: 12.0469  grad_norm:  1.8420  memory: 61.72GiB(77.99%)  tps: 297  tflops: 4.48  mfu: 1.43%
[rank0]:[titan] 2025-09-01 16:03:30,780 - root - INFO - Synchronizing and adjusting timeout for all ProcessGroups to 0:01:40
[rank0]:[titan] 2025-09-01 16:04:22,882 - root - INFO - step: 10  loss: 11.2800  grad_norm:  2.4321  memory: 70.02GiB(88.48%)  tps: 708  tflops: 10.65  mfu: 3.41%
```
https://www.internalfb.com/intern/perfdoctor/trace_view?filepath=tree/jw3468/20250904/sac_recompute.json.g …

Save _to_copy and a2a in selective AC policy

---

torchtitan/config/job_config.py
torchtitan/models/llama3/model/model.py
torchtitan/tools/utils.py
torchtitan/train.py

This PR adds support for full bfloat16 training. In SFT it is pretty common to store everything in bfloat16 to save memory, with select tensors (logits, RoPE buffers and activations) maintained in a higher precision to preserve numerical accuracy. Separately I think having this supported more generally would be useful for faster iteration -- e.g. it allows me to run Llama3 70B on a single node of H100s, which otherwise is not possible with the default config.
Assuming this is generally useful, would like feedback on:
1) Acceptable loss convergence: in the first 100 steps on Llama3 8B full bf16 training goes from 12.25 -> 8, as opposed to 12.25 -> 7 with fp32 training. Is this a concern? (As mentioned, for SFT this is less of an issue; happy to validate that statement if that's helpful.) …

[RFC] Support full bf16 training

---

docs/datasets.md
tests/unit_tests/test_dataset_checkpointing.py
torchtitan/datasets/__init__.py
torchtitan/datasets/hf_datasets.py
torchtitan/experiments/flux/dataset/flux_dataset.py
torchtitan/experiments/flux/tests/unit_tests/test_flux_dataloader.py
torchtitan/experiments/multimodal/mm_dataset.py

As suggested in the comment [here](https://github.com/pytorch/torchtitan/pull/1615#discussion_r2342453286) for PR #1615 , I refactored all the dataset config instance to a common one in `torchtitan/datasets/__init__.py`, with a common name `sample_processor`.
Doing it here to make it easier to review and limit scope of the other PR.

refactor: use a common DatasetConfig class

---

torchtitan/tools/utils.py

Not high priority, just something I noticed as I was using the GC util.

Grammatical updates to GC logging

---

torchtitan/components/validate.py
torchtitan/distributed/pipeline_parallel.py
torchtitan/experiments/deepseek_v3/train_ds_dev.py
torchtitan/experiments/forge/example_train.py
torchtitan/train.py

[problem]
Using gradient accumulation is incompatible with PipleineSchedule(..., scale_grads=True) option, which defaults to True.
When this option is set, at each step, all gradients are scaled by the micro-batch size. This works fine for a single gradient accumulation step, but when using multiple steps, this will rescale the total gradient by this factor, not just at the end of gradient accumulation.
The result is that the accumulated gradient is an exponential moving average, rather than a sum. Overall, the resulting gradients are much smaller than they should be and using gradient accumulation with PP is not equivalent to using it without PP -- the loss curves diverge substantially, as well as the gradient-norms are way off.
A secondary consequence of is that at every step, it …

fix: pp grad accumulation is broken

---

torchtitan/config/job_config.py
torchtitan/experiments/llama4/model/args.py
torchtitan/experiments/qwen3/model/args.py
torchtitan/models/deepseek_v3/model/args.py
torchtitan/models/moe.py

we can set `DEBUG_FORCE_LOAD_BALANCED=1` to force each experts get same amount of tokens. 
reprodue: `DEBUG_FORCE_LOAD_BALANCED=1 CONFIG_FILE="./torchtitan/models/deepseek_v3/train_configs/debug_model.toml" NGPU=4 ./run_train.sh --compile.enable`
here is test on 8layers, 8 activate and 64 total experts.  Green one is vanilla one and purple one is with force load balance

 Fake balanced routing in MoE

---

torchtitan/models/deepseek_v3/train_configs/deepseek_v3_16b.toml
torchtitan/models/deepseek_v3/train_configs/deepseek_v3_671b.toml

As #1789 mentioned, make the 16B default toml config safe for 80GB H100 as well.

Set proper deepseek-v3 16b parameters

---

torchtitan/models/attention.py
torchtitan/train.py

This code logic was committed prematurely as the final CP UX may be different. Remove it for now to avoid confusion and future BC issues.

Remove create_cp_block_mask

---

docs/debugging.md
tests/unit_tests/test_checkpoint.py
torchtitan/components/checkpoint.py
torchtitan/config/job_config.py

Seed checkpoint loading requires checkpoint.enable to be True.  However, when using seed checkpoints, users typically don't want to save subsequent checkpoints since seed checkpoints serve verification purposes only.

Provide load_seed_checkpoint_only option
